# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
reviews:
  profile: "assertive"
  high_level_summary: true
  collapse_walkthrough: true
  path_filters:
    - "!docs/**"
    - "!.specify/**"
    - "!**/*.md"
    - "!**/mock-data/**"
  auto_review:
    enabled: true
    drafts: true
chat:
  auto_reply: true
