package cli

func capabilityCatalogRecordsPart2() []capabilityRecord {
	return []capabilityRecord{
		capability(
			"reconcile",
			"Inspect & Repair",
			"Reconcile Kit-managed project files, rules, and documentation drift.",
			mutationWritesFiles,
			withNetwork("fetches the Kit ruleset registry when managed files are included"),
			withFileWrites("without --include-files, default and prompt-only reconciliation emit a coding-agent prompt and do not write files", "--include-files applies Kit-managed file, ruleset, README, config, init scaffold, and instruction refreshes; --dry-run previews them without writing files"),
			withGitMutation("none"),
			withFlags(
				flag("--include-files", "include Kit-managed file and ruleset refreshes before auditing docs"),
				flag("--all", "make whole-project reconcile explicit; combine with --include-files for scaffold refreshes"),
				flag("--force", "force included Kit-managed file and ruleset refreshes", "review local edits first"),
				flag("--dry-run", "preview included file refreshes without writing files", "read-only"),
				flag("--diff", "print planned included file refreshes as a unified diff with --dry-run", "read-only"),
				flag("--file", "limit included refresh to one Kit-managed file; repeat for multiple files"),
				flag("--output-only", "print prompt text or refresh preview to stdout instead of copying"),
				flag("--copy", "copy prompt even with --output-only"),
				flag("--migrate-references", "include instructions for migrating deprecated front matter dependencies to references"),
				flag("--migrate-verification", "include advisory instructions for adding executable verification fields to active tasks"),
			),
			withRelated(
				related("status", "reports whether managed-file refresh or attention is needed"),
				related("check", "validates known invariants"),
				related("init --refresh", "lower-level compatibility path used by reconcile for managed-file refreshes"),
				related("project refresh", "semantic Constitution refresh after structural reconcile is clean"),
			),
			withWhenToUse(
				"Use as the reviewed surface for bringing a Kit-managed project up to date with current files, rules, and scaffold behavior.",
				"Run interactively to answer include files?, force these changes?, and output coding-agent prompt too?",
				"Use `--include-files --dry-run --diff` to preview structural refreshes before applying them.",
			),
			withWhenNotToUse(
				"Do not use as a GitHub delivery command; it does not stage, commit, push, or open PRs.",
				"Do not choose force until local generated-doc, ruleset, or workflow edits have been reviewed.",
			),
			withExamples("kit reconcile", "kit reconcile --all --include-files", "kit reconcile --include-files --dry-run --diff", "kit reconcile --include-files", "kit reconcile --include-files --force", "kit reconcile --output-only"),
		),
		capability(
			"instructions",
			"Prompt Utilities",
			"Print versioned provider-neutral coding-agent instructions as raw Markdown.",
			mutationNone,
			withFlags(flag("--version", "select an exact immutable vN version; defaults to the current version", "read-only")),
			withRelated(
				related("prompt", "renders reusable task-specific and compatibility prompts"),
				related("scaffold agents", "writes repository-specific agent instruction files"),
			),
			withWhenToUse(
				"Use when adding Kit's shared system-level coding-agent policy directly to Codex, Claude, or GitHub Copilot.",
				"Omit --version for the current policy or pass --version=vN to reproduce an earlier release.",
			),
			withWhenNotToUse(
				"Do not use to create or refresh repository-specific AGENTS.md, CLAUDE.md, or Copilot files; use `kit scaffold agents`.",
				"Do not use for a task-specific reusable prompt; use `kit prompt`.",
			),
			withExamples("kit instructions", "kit instructions --version=v3", "kit instructions --version=v2"),
			withCaveats(
				"The command writes only raw Markdown to stdout and never copies to the clipboard.",
				"All versions are embedded in the installed binary; selection performs no network or project configuration access.",
			),
		),
		capability("prompt", "Prompt Utilities", "Work with Kit prompt templates.", mutationNone, withFlags(flag("--output-only", "print prompt text instead of copying it with metadata"), flag("--copy", "copy prompt even with --output-only")), withRelated(related("prompt list", "lists available prompts, including the legacy V2 supervisor entry"), related("spec", "scaffolds or adopts living repository memory"), related("set prompt", "sets prompt preferences")), withWhenToUse("Use to render reusable support and compatibility prompts.", "Use this catalog entry when looking for the former kit spec prompt behavior."), withExamples("kit prompt list", "kit prompt kit spec", "kit prompt workflow spec --output-only"), withCaveats("`kit prompt kit spec` is legacy V2 compatibility; plain `kit spec <feature>` uses native-planning orientation.")),
		capability("prompt list", "Prompt Utilities", "List available Kit prompt templates, including the legacy V2 supervisor entry.", mutationNone, withRelated(related("prompt", "renders prompt templates"), related("spec", "creates or adopts SPEC.md when durable memory is needed")), withExamples("kit prompt list")),
		capability("set", "Prompt Utilities", "Update Kit configuration values.", mutationWritesFiles, withFileWrites("writes Kit local or global configuration"), withRelated(related("set prompt", "sets prompt-related configuration"))),
		capability("set prompt", "Prompt Utilities", "Set the active prompt preference.", mutationWritesFiles, withFileWrites("writes Kit prompt configuration"), withRelated(related("prompt list", "find prompt names before setting one"))),
		capability("handoff", "Prompt Utilities", "Generate handoff context for continuing work.", mutationNone, withRelated(related("summarize", "condenses project or feature context"))),
		capability("summarize", "Prompt Utilities", "Summarize Kit project or feature context.", mutationNone, withRelated(related("handoff", "packages summary for a continuation"))),
		capability("dispatch", "Prompt Utilities", "Build Agent Team Plan prompts for agents, PR review threads, and CodeRabbit prompt-prep intake.", mutationGit, withNetwork("none by default", "--pr fetches unresolved, non-outdated review threads and PR-head metadata and fetches origin; --loop can poll CodeRabbit; --resolve --yes mutates GitHub review-thread state"), withFileWrites("none for generic prompt generation", "--pr may create the canonical PR-head worktree and link the primary checkout's exact .env; editor and clipboard flags affect output outside project files"), withGitMutation("none for generic prompt generation", "--pr prompt generation may fetch origin and add or attach the exact PR-head worktree; --resolve mutates GitHub only"), withFlags(flag("--pr", "prefill from unresolved, non-outdated PR review threads and resolve the exact writable PR-head worktree", "conditional worktree creation; refuses forks and prompts before including dirty changes"), flag("--loop", "route PR review feedback through the prompt-prep review-loop workflow"), flag("--coderabbit", "with --pr, keep CodeRabbit-authored comments and extract Prompt for AI Agents blocks"), flag("--resolve", "with --pr, resolve matching unresolved review threads after fixes or no-op decisions are complete", "GitHub mutation; requires --yes"), flag("--yes", "confirm --resolve after fixes or no-op decisions are complete", "required for mutation"), flag("--watch", "with --loop, wait for current-head CodeRabbit review completion", "network read with polling"), flag("--copy", "copy generated prompt output"), flag("--output-only", "print prompt without wrapper text"), flag("--max-subagents", "bound the generated dispatch queue; default 3, hard ceiling 4")), withRelated(related("loop review", "coding-agent correctness repair loop"), related("ci", "inspects CI context"), related("code-review", "builds review-focused prompts")), withExamples("kit dispatch --file tasks.md", "kit dispatch --pr 14 --coderabbit", "kit dispatch --loop --pr 14 --watch", "kit dispatch --pr 14 --resolve --yes"), withCaveats("Generic dispatch remains prompt-only and normalizes its working directory to the current Git top-level.", "PR prompt generation reuses or creates the exact same-repository PR-head worktree, records remote/local head SHAs and the push target, and carries the user's dirty-change inclusion choice into the prompt.", "`--resolve --yes` is the explicit GitHub mutation path for already-handled review threads.", "Generated dispatch prompts require one accountable supervisor, an Agent Team Plan before subagent execution, default max 3 concurrent subagents, and hard ceiling 4.")),
		capability("code-review", "Prompt Utilities", "Generate a read-only, finding-oriented review prompt for the current branch change set.", mutationNone, withRelated(related("dispatch", "routes prompts to specialized agents"), related("legacy verify", "runs executable checks")), withCaveats("The prompt reports only evidence-backed actionable findings in severity order and does not add generic subagent implementation guidance.")),
		capability("skill", "Prompt Utilities", "Inspect or generate Kit skill prompts.", mutationNone, withRelated(related("skill mine", "mines local context for skill material"))),
		capability("skill mine", "Prompt Utilities", "Mine repository context for reusable skill material.", mutationNone, withFileWrites("none by default", "shared editor flags can copy or write generated prompt output"), withFlags(flag("--copy", "copy generated prompt output"), flag("--output-only", "print prompt without wrapper text")), withRelated(related("skill", "skill command group"))),
		capability("upgrade", "Utilities", "Upgrade the Kit CLI installation.", mutationNetwork, withNetwork("downloads release metadata or binaries"), withFileWrites("writes the installed Kit binary or related install files"), withFlags(flag("--check", "check for an upgrade without installing when supported", "prefer for read-only inspection")), withRelated(related("version", "shows current installed version"))),
		capability("version", "Utilities", "Print the Kit CLI version.", mutationNone, withRelated(related("upgrade", "updates the installed version"))),
		capability("completion", "Utilities", "Generate shell completion scripts.", mutationNone, withFileWrites("none by default", "the shell may redirect output to a completion file outside Kit"), withRelated(related("help", "shows command syntax"))),
		capability(
			"git wt list",
			"Utilities",
			"Select or print registered worktrees, newest first by full commit timestamp.",
			mutationNone,
			withFileWrites("none"),
			withGitMutation("none; reads registered worktree metadata, status, and commit dates only"),
			withFlags(
				flag("--sort", "order by updated (default), state, head, or path"),
				flag("--reverse", "reverse the selected sort order"),
				flag("--plain", "print the table instead of opening the terminal selector"),
			),
			withRelated(related("git wt cd", "opens a child shell for an exact lane"), related("git wt path", "prints an exact lane path for parent-shell navigation")),
			withWhenToUse("Use interactively to choose a registered worktree with arrow keys or Tab.", "Use with --plain or redirected output when a script or terminal needs the table."),
			withWhenNotToUse("Do not expect the selected child shell to change the parent shell's directory.", "Do not use as a policy dependency; native git worktree commands remain authoritative."),
			withExamples("git wt list", "git wt list --plain --sort path", "git wt list --sort state --reverse"),
			withCaveats("Terminal selection uses color and opens the configured shell in the chosen worktree.", "Non-terminal input or output automatically uses the stable plain table.", "The default ordering is newest first by full commit timestamp; --sort state, --sort head, and --sort path select alternate orderings.", "LAST UPDATED is display-only and shown at day precision."),
		),
		capability(
			"git wt cd",
			"Utilities",
			"Open an interactive shell in an exact registered worktree lane.",
			mutationNone,
			withGitMutation("none; reads registered worktree metadata only"),
			withWhenToUse("Use for manual testing when you want a shell rooted in an existing lane."),
			withWhenNotToUse("Do not expect this child shell to change the parent shell's directory; use `git wt path` with `cd` for that."),
			withExamples("git wt cd GH-101"),
			withCaveats("The command starts the configured `$SHELL` (or `/bin/sh`) with the lane as its working directory and returns when that shell exits.", "The lane must already be an exact registered worktree."),
		),
		capability(
			"git wt path",
			"Utilities",
			"Print the exact registered worktree path for a lane.",
			mutationNone,
			withGitMutation("none; reads registered worktree metadata only"),
			withWhenToUse(
				"Use in shell command substitution to navigate to an existing lane.",
				"Use when scripts need the canonical path of an exact registered lane.",
			),
			withWhenNotToUse(
				"Do not expect an external command to change the parent shell's directory.",
				"Do not use for fuzzy lane discovery; use `git wt list` to inspect registered worktrees.",
			),
			withExamples(`cd "$(git wt path GH-101)"`, `git -C "$(git wt path GH-101)" status`),
			withCaveats(
				"The command is read-only and rejects unregistered lanes or traversal instead of guessing.",
				"`git wt` is an optional manual convenience; Kit-managed rules and reconciled guidance use native `git worktree` commands.",
			),
		),
		capability("help", "Utilities", "Show command help and flag syntax.", mutationNone, withRelated(related("capabilities", "adds behavior and safety metadata"))),
	}
}
