package cli

func workflowCapabilityRecords() []capabilityRecord {
	return []capabilityRecord{
		capability("spec", "Agent Workflow", "Create or adopt a living V3 feature specification.", mutationWritesFiles,
			withFileWrites("creates docs/specs/<feature>/SPEC.md when absent and updates PROJECT_PROGRESS_SUMMARY.md", "existing V1 and V2 specs are preserved without mechanical rewriting"),
			withRelated(related("context resolve", "selects the feature and its evidence"), related("status", "reports feature state")),
			withWhenToUse("Use for feature work with material rationale that must survive the agent session."),
			withWhenNotToUse("Do not use it to launch an agent or perform Git delivery."),
			withExamples("kit spec invitation-flow")),
		capability("context", "Agent Workflow", "Resolve repository-local coding-agent context.", mutationNone,
			withNetwork("none"), withFileWrites("none"), withGitMutation("none"),
			withRelated(related("context resolve", "returns the deterministic evidence contract")),
			withWhenToUse("Use this group to discover deterministic repository-local context commands."),
			withWhenNotToUse("Invoke `kit context resolve` to produce a context contract; the group itself only shows command help."),
			withExamples("kit context resolve --json")),
		capability("context resolve", "Agent Workflow", "Resolve ordered workflows, rules, specs, strategies, and implementation evidence.", mutationNone,
			withNetwork("none"), withFileWrites("none"), withGitMutation("none"),
			withFlags(flag("--workflow", "select a local workflow"), flag("--feature", "include feature and related historical specs"), flag("--path", "add a required repository-confined path hint"), flag("--json", "emit kit.context/v1 JSON", "read-only")),
			withWhenToUse("Run before coding-agent work and rerun after material scope changes."),
			withWhenNotToUse("Do not use it for network access, model inference, agent launch, Git mutation, or writes."),
			withExamples("kit context resolve --workflow implementation-delivery --feature invitation-flow --json"),
			withCaveats("Missing or invalid required local evidence returns blocked JSON and exit status 2.")),
		capability("dispatch", "Agent Workflow", "Produce an accountable Agent Team Plan prompt or PR-feedback repair prompt.", mutationGit,
			withNetwork("none for file/stdin input", "--pr reads GitHub review data; --loop --watch performs bounded status polling"),
			withFileWrites("generic prompt generation writes no project files", "PR mode may prepare the exact writable same-repository PR-head worktree"),
			withGitMutation("none for generic input", "PR mode may fetch and attach/create the exact PR-head worktree; --resolve --yes explicitly resolves verified threads"),
			withFlags(flag("--coderabbit", "with --pr, include only CodeRabbit-authored review comments"), flag("--copy", "copy the prompt even with --output-only"), flag("--editor", "open interactive input in a specific editor command"), flag("--file", "read task input from a file"), flag("--loop", "use asynchronous review-loop intake"), flag("--output-only", "print prompt output"), flag("--pr", "ingest active PR review feedback"), flag("--resolve", "resolve verified handled threads", "GitHub mutation with --yes"), flag("--vim", "open interactive input in a vim-compatible editor"), flag("--watch", "with --loop, wait for current-head review completion"), flag("--yes", "confirm --resolve without prompting", "required for noninteractive thread resolution")),
			withRelated(related("pr fix", "friendly PR-feedback entrypoint"), related("context resolve", "loads pr-feedback-repair rules"))),
		capability("instructions", "Agent Workflow", "Print immutable provider-neutral coding-agent instructions.", mutationNone,
			withFlags(flag("--version", "select an exact instruction version")),
			withExamples("kit instructions", "kit instructions --version v5"),
			withCaveats("Output is raw Markdown on stdout and requires no project root.")),
	}
}
