package cli

func inspectionCapabilityRecords() []capabilityRecord {
	return []capabilityRecord{
		capability("status", "Inspect & Repair", "Show feature and Kit-managed project state.", mutationNetwork, withNetwork("fetches registry state with a bounded timeout; registry failure is reported as unknown"), withFlags(flag("--json", "emit machine-readable status"), flag("--all", "show all feature state")), withRelated(related("reconcile", "repairs managed drift"))),
		capability("registry", "Inspect & Repair", "Inspect the configured Kit registry.", mutationNone, withNetwork("none"), withFileWrites("none"), withGitMutation("none"), withRelated(related("registry status", "reports freshness and actions")), withWhenToUse("Use this group to discover registry inspection commands."), withWhenNotToUse("Invoke `kit registry status` to fetch and report registry freshness; the group itself only shows command help.")),
		capability("registry status", "Inspect & Repair", "Report registry and managed-file freshness.", mutationNetwork, withNetwork("fetches the configured rules registry unless managed health is disabled"), withFlags(flag("--json", "emit machine-readable status", "read-only")), withRelated(related("health", "applies safe maintenance"))),
		capability("health", "Inspect & Repair", "Apply safe managed updates and validate project health.", mutationWritesFiles, withNetwork("fetches the configured rules registry"), withFileWrites("applies conflict-free managed updates", "--dry-run and --diff do not write; custom and conflicting content is preserved"), withFlags(flag("--dry-run", "preview without writes", "read-only"), flag("--diff", "show dry-run diff", "read-only"), flag("--json", "emit machine-readable results")), withRelated(related("usage report", "weekly maintenance reads aggregate usage once"), related("reconcile", "curates unresolved drift"))),
		capability("capabilities", "Inspect & Repair", "Describe exact supported commands, side effects, and safety behavior.", mutationNone, withFlags(flag("--json", "emit machine-readable records"), flag("--full", "include full supported records"), flag("--search", "search supported records")), withRelated(related("context resolve", "selects local evidence after command choice"))),
		capability("usage", "Inspect & Repair", "Report bounded private local command usage data.", mutationNone, withNetwork("none"), withFileWrites("none"), withGitMutation("none"), withFlags(flag("--since", "bound report history"), flag("--command", "filter by normalized command"), flag("--project", "filter by anonymized project"), flag("--json", "emit machine-readable results")), withRelated(related("usage refresh", "applies bounded local storage maintenance"), related("usage clear", "removes selected local history")), withWhenToUse("Use without a subcommand as the read-only aggregate usage report."), withWhenNotToUse("Use the explicit refresh, clear, enable, or disable subcommand when local usage state should change."), withExamples("kit usage --since 30d --json"), withCaveats("Usage commands do not record themselves; no arguments, values, paths, output, prompts, environment, URLs, or secrets are collected.")),
		capability("usage report", "Inspect & Repair", "Aggregate bounded local command usage.", mutationNone, withFlags(flag("--since", "report window such as 90d"), flag("--command", "command filter"), flag("--project", "anonymized project filter"), flag("--json", "emit JSON"))),
		capability("usage status", "Inspect & Repair", "Show effective collection settings, coverage, bounds, and diagnostics.", mutationNone, withFlags(flag("--json", "emit JSON"))),
		capability("usage refresh", "Inspect & Repair", "Validate, rotate, and prune bounded usage storage.", mutationWritesFiles, withNetwork("none"), withFileWrites("may rotate usage shards and prune events beyond the bounded retention limits", "--dry-run validates and reports without writing"), withFlags(flag("--dry-run", "preview maintenance", "read-only"), flag("--json", "emit JSON")), withWhenToUse("Use to validate local usage storage and apply its size and retention bounds."), withWhenNotToUse("Use `kit usage status` for a read-only status view without maintenance."), withExamples("kit usage refresh --dry-run --json"), withCaveats("Usage maintenance is local-only and does not transmit telemetry.")),
		capability("usage clear", "Inspect & Repair", "Clear selected local usage events.", mutationDestructive, withNetwork("none"), withFileWrites("rewrites local usage shards to remove matching events; --all removes all recorded usage history"), withFlags(flag("--all", "clear all history"), flag("--command", "clear one normalized command"), flag("--json", "emit JSON"), flag("--project", "clear one anonymized project or the current project"), flag("--yes", "confirm non-interactively", "destructive")), withWhenToUse("Use to remove selected private local usage history."), withWhenNotToUse("Do not use for retention maintenance; use `kit usage refresh` instead."), withExamples("kit usage clear --project current", "kit usage clear --all --yes --json"), withCaveats("Without --all, --command, or --project, the command targets the current project's anonymized usage identity and asks for confirmation unless --yes is set.")),
		usageToggleCapabilityRecord("enable", true),
		usageToggleCapabilityRecord("disable", false),
		capability("config", "Inspect & Repair", "Inspect Kit project configuration commands.", mutationNone, withNetwork("none"), withFileWrites("none"), withGitMutation("none"), withRelated(related("config check", "validates and offers bounded repairs")), withWhenToUse("Use this group to discover project-configuration checks."), withWhenNotToUse("Invoke `kit config check` to validate or repair configuration; the group itself only shows command help.")),
		capability("config check", "Inspect & Repair", "Validate .kit.yaml and offer safe bounded repairs.", mutationWritesFiles, withNetwork("none on a complete fast path", "interactive AWS remediation may list profiles, verify STS identity, and discover enabled Regions"), withFileWrites("interactive repairs may update schema, AWS profile, account, and Region fields", "--json is read-only"), withFlags(flag("--json", "validate without prompts or writes", "read-only"))),
		capability("aws", "Inspect & Repair", "Inspect project-bound AWS verification commands.", mutationNone, withNetwork("none"), withFileWrites("none"), withGitMutation("none"), withRelated(related("aws verify", "checks exact identity")), withWhenToUse("Use this group to discover AWS context verification commands."), withWhenNotToUse("Invoke `kit aws verify` for the STS identity check; the group itself only shows command help.")),
		capability("aws verify", "Inspect & Repair", "Verify configured AWS profile, account, and Region through STS.", mutationNetwork, withNetwork("calls aws sts get-caller-identity using the configured profile and Region"), withFlags(flag("--json", "emit verified identity"))),
		capability("check", "Inspect & Repair", "Validate feature or whole-project Kit contracts.", mutationNone, withFlags(flag("--all", "check all features"), flag("--project", "check the project contract"))),
		capability("pr", "Inspect & Repair", "Discover pull-request repair and release-orchestration prompts.", mutationNone, withNetwork("none"), withFileWrites("none"), withGitMutation("none"), withRelated(related("pr fix", "collects active feedback and prepares the repair lane"), related("pr orchestrate", "renders a dependency-aware release prompt")), withWhenToUse("Use this group to choose between PR feedback repair and release orchestration."), withWhenNotToUse("Invoke a concrete PR subcommand to read GitHub or prepare a worktree; the group itself only shows command help.")),
		capability("pr fix", "Inspect & Repair", "Collect active PR feedback and produce a coding-agent repair prompt.", mutationGit, withNetwork("lists/fetches GitHub PRs and paginated active review threads"), withFileWrites("prompt-only by default", "may prepare the exact writable same-repository PR-head worktree"), withGitMutation("may fetch and create/attach the exact PR-head worktree; never edits source, stages, commits, pushes, comments, resolves, or merges"), withFlags(flag("--pr", "target URL, Markdown link, owner/repo#number, or current-repo number"), flag("--coderabbit", "filter to CodeRabbit"), flag("--copy", "copy the prompt even with --output-only"), flag("--edit", "edit collected tasks"), flag("--editor", "edit collected tasks with a specific editor command"), flag("--output-only", "print prompt"), flag("--vim", "edit collected tasks with a vim-compatible editor"), flag("--max-subagents", "default 3, hard ceiling 4")), withRelated(related("context resolve", "loads pr-feedback-repair evidence"), related("dispatch", "provides explicit thread resolution"))),
		capability("pr orchestrate", "Inspect & Repair", "Resolve bounded repository scope into a release-orchestration prompt.", mutationNetwork,
			withNetwork("none when local Git metadata is sufficient", "may run one cached targeted gh repo view per repository when identity or default-branch evidence is missing"),
			withFileWrites("none; dry-run and normal generation do not write repositories"),
			withGitMutation("none; Kit does not enumerate, edit, merge, deploy, or mutate release state"),
			withFlags(flag("--context", "optional feature or release context"), flag("--copy", "copy in addition to output"), flag("--dry-run", "emit resolved YAML provenance and prompt without clipboard access", "read-only"), flag("--environment", "single target environment"), flag("--infra", "auto, none, direct, iac, mixed, or custom"), flag("--infra-cli", "infrastructure CLI or source-of-truth command"), flag("--infra-provider", "infrastructure provider"), flag("--integration-suite", "auto, tagged mechanism, or none"), flag("--organization", "source-control organization"), flag("--output-only", "print raw prompt"), flag("--project", "project or release program name"), flag("--repos", "repeat exact repository paths"), flag("--root", "scan only the root and immediate child repositories"), flag("--scope", "strict, related, or organization expansion"), flag("--verify", "auto or a tagged verification mechanism")),
			withRelated(related("context resolve", "loads release-orchestration and pull-request-merge evidence"), related("pr fix", "repairs review feedback before readiness"), related("dispatch", "supports bounded execution topology")),
			withWhenToUse("Use when a coding agent should construct and execute an authorized dependency-aware multi-repository release plan."),
			withWhenNotToUse("Do not use it as a release executor; Kit generates instructions but does not enumerate PRs, merge, deploy, mutate infrastructure, or launch an agent."),
			withExamples("kit pr orchestrate --repos ./service-a --repos ./service-b --verify auto --dry-run"),
			withCaveats("Only filename-level clues and sanitized repository metadata are discovered; arguments, paths, and prompt contents are excluded from usage telemetry.")),
		capability("improve", "Inspect & Repair", "Discover Kit's deterministic benchmark harness workflows.", mutationNone, withNetwork("none"), withFileWrites("none"), withGitMutation("none"), withFlags(flag("--json", "emit machine-readable output from the selected improve workflow")), withRelated(related("improve run", "runs a benchmark suite")), withWhenToUse("Use this group to discover benchmark-backed improvement workflows."), withWhenNotToUse("Invoke `kit improve run` to execute a benchmark suite; the group itself only shows command help.")),
		capability("improve run", "Inspect & Repair", "Run a deterministic Kit benchmark suite in disposable fixtures.", mutationExecutesCommands, withFileWrites("writes .kit/improve run evidence", "--dry-run does not write"), withFlags(flag("--suite", "select suite"), flag("--kit-binary", "evaluate an exact binary"), flag("--dry-run", "plan without writes", "read-only"), flag("--json", "emit the run manifest"))),
		capability("rules", "Inspect & Repair", "Discover durable repository-local ruleset commands.", mutationNone, withNetwork("none"), withFileWrites("none"), withGitMutation("none"), withRelated(related("rules list", "lists local rulesets"), related("rules add", "imports or creates a ruleset"), related("rules link", "links a ruleset to a feature")), withWhenToUse("Use this group to choose a ruleset inspection or mutation command."), withWhenNotToUse("Invoke a concrete rules subcommand to inspect or change project state; the group itself only shows command help.")),
		rulesAddCapabilityRecord(),
		capability("rules list", "Inspect & Repair", "List durable repository-local rulesets and their tracked registry state.", mutationNone, withNetwork("none"), withFileWrites("none"), withGitMutation("none"), withWhenToUse("Use to inspect rulesets already materialized in the current project."), withWhenNotToUse("Use `kit rules add` to browse or import the remote Kit rules registry."), withExamples("kit rules list")),
		capability("rules view", "Inspect & Repair", "Inspect a local or registry ruleset.", mutationNetwork, withNetwork("none when the ruleset exists locally; otherwise fetches the downstream Kit rules registry with a bounded timeout"), withFileWrites("none"), withGitMutation("none"), withWhenToUse("Use to inspect one ruleset before importing or linking it."), withWhenNotToUse("Use `kit rules list` for a local inventory without registry fallback."), withExamples("kit rules view source-file-size"), withCaveats("Kit-maintainer-only registry rules are hidden from downstream projects.")),
		capability("rules link", "Inspect & Repair", "Link a ruleset through canonical feature references.", mutationWritesFiles, withNetwork("none"), withFileWrites("updates the resolved feature document's canonical front matter reference when needed"), withGitMutation("none"), withFlags(flag("--read-policy", "set the feature reference policy to must or conditional")), withWhenToUse("Use after a local ruleset exists and should govern one feature."), withWhenNotToUse("Do not use to copy ruleset text into always-loaded instruction files."), withExamples("kit rules link invitation-flow source-file-size --read-policy must"), withCaveats("The feature and ruleset must already exist and validate successfully.")),
		reconcileCapabilityRecord(),
	}
}

func usageToggleCapabilityRecord(command string, enabled bool) capabilityRecord {
	action := "Enable"
	state := "enabled"
	if !enabled {
		action = "Disable"
		state = "disabled"
	}
	return capability("usage "+command, "Inspect & Repair", action+" local usage collection at project or global scope.", mutationWritesFiles,
		withNetwork("none"),
		withFileWrites("updates the selected project or machine-wide local usage configuration"),
		withGitMutation("none"),
		withFlags(flag("--global", "change machine-wide collection"), flag("--json", "emit JSON"), flag("--project", "change collection for the current Kit project")),
		withWhenToUse("Use to mark local usage collection "+state+" at exactly one scope."),
		withWhenNotToUse("Do not pass both --global and --project; exactly one scope is required."),
		withExamples("kit usage "+command+" --project --json"),
		withCaveats("A global disable is absolute; a project cannot override it."))
}

func rulesAddCapabilityRecord() capabilityRecord {
	return capability("rules add", "Inspect & Repair", "Import or create a durable repository-local ruleset.", mutationWritesFiles,
		withNetwork("without a slug, fetches the downstream Kit rules registry unless --custom or another interactive-creation option is selected"),
		withFileWrites("creates or updates docs/references/rules/<slug>.md and, for registry selection, updates .kit.yaml registry provenance"),
		withGitMutation("none"),
		withFlags(flag("--conditional", "set the default read policy to conditional"), flag("--copy", "copy the optimization prompt even with --output-only"), flag("--custom", "open the interactive custom ruleset builder"), flag("--editor", "open custom context in a specific editor command"), flag("--evidence", "set the default read policy to evidence"), flag("--force", "overwrite an existing ruleset file", "review local customizations first"), flag("--inline", "capture custom context inline"), flag("--must", "set the default read policy to must"), flag("--output-only", "print the optimization prompt"), flag("--skip", "set the default read policy to skip"), flag("--vim", "open custom context in a vim-compatible editor")),
		withRelated(related("rules view", "inspects a ruleset before import"), related("rules link", "attaches an installed ruleset to a feature")),
		withWhenToUse("Use with a slug for local scripted creation, or without a slug to import from the registry or build a custom ruleset interactively."),
		withWhenNotToUse("Do not use --force without reviewing existing local content; use `kit rules view` for read-only inspection."),
		withExamples("kit rules add source-file-size", "kit rules add", "kit rules add --custom --output-only"),
		withCaveats("Editor and clipboard behavior is limited to interactive custom creation; registry selection can activate, deactivate, import, or refresh selected managed rulesets."))
}

func reconcileCapabilityRecord() capabilityRecord {
	return capability("reconcile", "Inspect & Repair", "Reconcile managed files, rules, and documentation drift.", mutationWritesFiles,
		withNetwork("fetches the registry only when managed files are included"),
		withFileWrites("default and --prompt-only generate guidance without project writes", "--include-files applies existing conflict-aware refresh behavior; --dry-run previews"),
		withGitMutation("none"),
		withFlags(flag("--include-files", "include managed refresh"), flag("--all", "whole-project audit"), flag("--force", "force selected managed refresh"), flag("--dry-run", "preview without writes", "read-only"), flag("--diff", "show dry-run diff", "read-only"), flag("--file", "limit managed paths"), flag("--output-only", "print prompt"), flag("--copy", "copy prompt"), flag("--migrate-references", "include legacy reference migration guidance"), flag("--migrate-verification", "include legacy verification guidance"), flag("--prompt-only", "generate guidance without mutation", "read-only")),
		withRelated(related("health", "applies safe scheduled maintenance"), related("context resolve", "loads repository-maintenance evidence")),
		withWhenToUse("Use whole-project reconcile to audit every version-control-eligible handwritten source and test file against the exact 300-physical-line limit."),
		withCaveats(
			"The existing conflict-aware reconcile behavior and flags are preserved.",
			"V3 whole-project reconciliation checks `AGENTS.md` for the ordered Codex pre-response thread-title and thread-pin gate, including fail-visible first-commentary semantics.",
			"Whole-project output emits literal `source-file-size audit: complete` evidence with candidate, eligible-file, and violation counts; missing or incomplete evidence cannot support a clean result.",
		))
}
