package cli

func legacyCapabilityRecords() []capabilityRecord {
	return []capabilityRecord{
		capability("legacy brainstorm", "Legacy", "Legacy staged workflow: create or inspect the brainstorm artifact for a feature.", mutationWritesFiles, withFileWrites("writes docs/specs/<feature>/BRAINSTORM.md when generating"), withRelated(related("spec", "creates living feature memory when required")), withWhenNotToUse("Do not use as the default entry point; use native planning unless intentionally continuing staged work or backlog research.")),
		capability("legacy plan", "Legacy", "Legacy staged workflow: create or update an implementation plan from a feature spec.", mutationWritesFiles, withFileWrites("writes docs/specs/<feature>/PLAN.md"), withRelated(related("spec", "captures an accepted native plan when durable rationale exists"), related("legacy tasks", "legacy staged workflow breaks the plan into executable tasks")), withWhenNotToUse("Do not use for current feature design; use the host agent's native planning capability.")),
		capability("legacy tasks", "Legacy", "Legacy staged workflow: create or update the task list for a feature.", mutationWritesFiles, withFileWrites("writes docs/specs/<feature>/TASKS.md"), withRelated(related("spec", "does not require V3 task-checklist bureaucracy"), related("legacy implement", "legacy staged workflow uses tasks as the execution checklist")), withWhenNotToUse("Do not add a durable checklist solely for current V3 process.")),
		capability("legacy implement", "Legacy", "Legacy staged workflow: generate or print the implementation prompt for a feature.", mutationNone, withRelated(related("spec", "captures material repository memory"), related("legacy tasks", "legacy staged workflow defines the implementation checklist"), related("legacy verify", "legacy staged workflow validates completed work")), withWhenNotToUse("Do not use for current implementation from an accepted native plan.")),
		capability("legacy reflect", "Legacy", "Legacy staged workflow: generate or print a reflection prompt for completed feature work.", mutationNone, withRelated(related("spec", "curates validation and actual outcome"), related("complete", "marks finished work after validation")), withWhenNotToUse("Do not use instead of current post-validation repository-memory curation.")),
		capability("legacy verify", "Legacy", "Run local implementation verification for legacy staged or internal evidence workflows.", mutationExecutesCommands, withFileWrites("writes verification run artifacts by default", "--dry-run and --no-write avoid run artifact writes"), withFlags(flag("--task", "limit verification to one task"), flag("--dry-run", "plan verification without executing commands", "read-only"), flag("--no-write", "avoid writing verification artifacts", "read-only"), flag("--allow-shell", "allow shell checks to execute", "executes local commands")), withRelated(related("spec", "records validation evidence when repository memory is required"), related("check", "validates docs before implementation verification"), related("complete", "uses validation as a completion gate")), withWhenNotToUse("Do not use as a mandatory standalone step; run validation appropriate to the implementation.")),
	}
}
