package cli

import (
	"sort"
)

const capabilitiesSchemaVersion = 1

func capabilityCatalog() []capabilityRecord {
	records := []capabilityRecord{
		capability(
			"init",
			"Setup",
			"Initialize or refresh Kit project scaffolding in a repository.",
			mutationWritesFiles,
			withNetwork(
				"fetches the Kit ruleset registry from GitHub during default initialization and refresh",
				"--refresh and --dry-run --refresh read the registry for refresh planning; README badge planning may query gh repo visibility when a GitHub repository is configured or discoverable",
			),
			withFileWrites(
				"writes .kit.yaml, Kit project files, README.md managed status badges and final Maintainers section, docs, instruction files, registry rulesets, and .github/workflows/auto-assign.yml",
				"--dry-run previews refresh changes without writing files; auto-assignment workflow assignees come from local github.default_assignees, then global ~/.config/kit/.kit.yaml, and no-op safely when none are configured; README badge URLs come from local github.repository or the origin GitHub remote; private repositories skip public Shields GitHub metadata badges and keep only native GitHub Actions workflow badges when a conventional workflow exists; README Maintainers uses the managed Jameson/jamesonstone attribution",
			),
			withFlags(
				flag("--refresh", "refresh Kit-managed files and backfill or upgrade generated .kit.yaml settings such as loop.agent.command, README.md managed badges and Maintainers section, and managed GitHub auto-assignment workflow content"),
				flag("--dry-run", "preview --refresh without writing files", "read-only"),
				flag("--diff", "print planned --refresh changes as a unified diff; requires --dry-run", "read-only"),
				flag("--file", "limit --refresh to one Kit-managed file; repeat for multiple files"),
				flag("--force", "replace existing generated files when supported", "review local edits first"),
			),
			withRelated(
				related("scaffold", "generates individual workflow artifacts"),
				related("reconcile", "preferred reviewed surface for managed-file refreshes and coding-agent follow-up prompts"),
				related("loop review", "uses the loop agent config seeded by managed-file refresh"),
				related("project refresh", "semantic Constitution refresh after the project matures"),
			),
			withWhenToUse(
				"Use once to initialize Kit scaffolding, instruction docs, registry rulesets, managed README badges, the final README Maintainers section, and the optional GitHub auto-assignment workflow in a repository.",
				"Use `kit reconcile` in an existing Kit project when you want the interactive include-files, force, and coding-agent prompt choices around managed-file refreshes.",
				"Use `kit init --refresh` as the lower-level compatibility path for direct managed-file refreshes.",
			),
			withWhenNotToUse(
				"Do not use for semantic project documentation refresh alone; use `kit project refresh`.",
				"Do not use `--force` until local generated-doc or workflow changes have been reviewed.",
				"Prefer `kit reconcile` when a human should choose whether to include files, force changes, or output the follow-up coding-agent prompt.",
			),
			withCaveats("The generated Constitution starter is a valid bootstrap state; the init prompt leaves project-specific sections unchanged until repository evidence demonstrates durable project-wide truth."),
			withExamples("kit init", "kit reconcile", "kit reconcile --include-files --dry-run --diff", "kit init --refresh", "kit init --refresh --file=README.md", "kit init --refresh --file=.github/workflows/auto-assign.yml"),
		),
		capability("scaffold", "Setup", "Generate workflow artifacts for Kit features.", mutationWritesFiles, withFileWrites("writes generated docs under selected project paths"), withRelated(related("scaffold agents", "writes repo agent instructions"))),
		capability("scaffold agents", "Setup", "Generate or refresh repo-local agent instruction files.", mutationWritesFiles, withFileWrites("writes AGENTS.md and docs/agents guidance"), withFlags(flag("--force", "replace existing agent guidance files", "review local edits first")), withRelated(related("init", "creates the broader project structure"))),
		capability("backlog", "Workflow", "Inspect and manage feature backlog entries.", mutationWritesFiles, withFileWrites("can update backlog state depending on subcommand and flags"), withRelated(related("resume", "selects paused or pending work"))),
		capability("legacy", "Workflow", "List deprecated v1 staged workflow commands retained for migration.", mutationNone, withRelated(related("spec", "scaffolds living repository memory around native planning")), withWhenToUse("Use when finishing existing BRAINSTORM.md / PLAN.md / TASKS.md staged work."), withWhenNotToUse("Do not use for new work; use native planning and `kit spec <feature>` only when material rationale needs persistence.")),
		capability("legacy brainstorm", "Legacy", "Legacy staged workflow: create or inspect the brainstorm artifact for a feature.", mutationWritesFiles, withFileWrites("writes docs/specs/<feature>/BRAINSTORM.md when generating"), withRelated(related("spec", "creates living feature memory when required")), withWhenNotToUse("Do not use as the default entry point; use native planning unless intentionally continuing staged work or backlog research.")),
		capability("legacy plan", "Legacy", "Legacy staged workflow: create or update an implementation plan from a feature spec.", mutationWritesFiles, withFileWrites("writes docs/specs/<feature>/PLAN.md"), withRelated(related("spec", "captures an accepted native plan when durable rationale exists"), related("legacy tasks", "legacy staged workflow breaks the plan into executable tasks")), withWhenNotToUse("Do not use for current feature design; use the host agent's native planning capability.")),
		capability("legacy tasks", "Legacy", "Legacy staged workflow: create or update the task list for a feature.", mutationWritesFiles, withFileWrites("writes docs/specs/<feature>/TASKS.md"), withRelated(related("spec", "does not require V3 task-checklist bureaucracy"), related("legacy implement", "legacy staged workflow uses tasks as the execution checklist")), withWhenNotToUse("Do not add a durable checklist solely for current V3 process.")),
		capability("legacy implement", "Legacy", "Legacy staged workflow: generate or print the implementation prompt for a feature.", mutationNone, withRelated(related("spec", "captures material repository memory"), related("legacy tasks", "legacy staged workflow defines the implementation checklist"), related("legacy verify", "legacy staged workflow validates completed work")), withWhenNotToUse("Do not use for current implementation from an accepted native plan.")),
		capability("legacy reflect", "Legacy", "Legacy staged workflow: generate or print a reflection prompt for completed feature work.", mutationNone, withRelated(related("spec", "curates validation and actual outcome"), related("complete", "marks finished work after validation")), withWhenNotToUse("Do not use instead of current post-validation repository-memory curation.")),
		capability("legacy verify", "Legacy", "Run local implementation verification for legacy staged or internal evidence workflows.", mutationExecutesCommands, withFileWrites("writes verification run artifacts by default", "--dry-run and --no-write avoid run artifact writes"), withFlags(flag("--task", "limit verification to one task"), flag("--dry-run", "plan verification without executing commands", "read-only"), flag("--no-write", "avoid writing verification artifacts", "read-only"), flag("--allow-shell", "allow shell checks to execute", "executes local commands")), withRelated(related("spec", "records validation evidence when repository memory is required"), related("check", "validates docs before implementation verification"), related("complete", "uses validation as a completion gate")), withWhenNotToUse("Do not use as a mandatory standalone step; run validation appropriate to the implementation.")),
		capability(
			"plan",
			"Prompt Utilities",
			"Work with plans produced by native coding agents.",
			mutationNone,
			withFileWrites("none; plan utilities may read and replace the macOS clipboard when explicitly invoked"),
			withRelated(
				related("plan challenge", "supplements a copied Codex plan for independent adversarial review"),
				related("legacy plan", "retains the deprecated staged PLAN.md generator"),
				related("spec", "persists accepted plan rationale only when repository memory is required"),
			),
			withWhenToUse("Use after a host agent such as Codex for Mac has produced a native plan."),
			withWhenNotToUse("Do not use as a plan generator; native coding agents own plan creation."),
			withExamples("kit plan challenge"),
			withCaveats("Kit never launches or calls a model through this command group."),
		),
		capability(
			"plan challenge",
			"Prompt Utilities",
			"Supplement a copied Codex plan with a paste-ready adversarial review prompt.",
			mutationNone,
			withFileWrites("none; reads the current macOS clipboard and replaces it with the generated prompt by default"),
			withFlags(
				flag("--output-only", "print the raw challenge prompt without replacing the clipboard", "read-only"),
				flag("--copy", "copy the challenge prompt even with --output-only"),
			),
			withRelated(
				related("plan", "lists native-plan utilities"),
				related("spec", "captures accepted material rationale after native planning"),
				related("legacy plan", "creates a deprecated staged PLAN.md artifact"),
			),
			withWhenToUse(
				"Use after copying the complete plan produced by Codex for Mac `/plan`.",
				"Paste the generated challenge prompt into a human-selected secondary model such as Claude.",
			),
			withWhenNotToUse(
				"Do not use when the clipboard does not contain the complete candidate plan.",
				"Do not use as model execution, desktop automation, or automatic review-result ingestion.",
			),
			withExamples("kit plan challenge", "kit plan challenge --output-only"),
			withCaveats(
				"Default execution explicitly reads and replaces the macOS clipboard; it does not watch the clipboard.",
				"The reviewer is instructed to return either IMPLEMENT THIS PLAN or paste-ready instructions for Codex's tell-what-to-do-different field.",
				"Kit does not persist the copied plan, access chat history, call the network, or launch a model.",
			),
		),
		capability(
			"spec",
			"Workflow",
			"Scaffold or orient a living specification for native agent planning.",
			mutationWritesFiles,
			withFileWrites(
				"writes docs/specs/<feature>/SPEC.md for workflow_version 3 when no spec exists",
				"preserves existing V1 and V2 specifications without mechanical migration",
				"creates feature notes/reference-material directories",
				"updates PROJECT_PROGRESS_SUMMARY.md and prints concise native-planning orientation",
				"--legacy-supervisor and former supervisor-only flags retain deprecated V2 behavior",
			),
			withFlags(
				flag("--legacy-supervisor", "run the deprecated V2 lifecycle supervisor"),
				flag("--prompt-only", "emit the v2 supervisor prompt for an existing feature without writing adoption changes or prompting", "read-only"),
				flag("--revise-thesis", "append a dated thesis note and refresh delivery intent before rendering the prompt"),
				flag("--output-only", "print the prompt instead of copying it"),
				flag("--copy", "copy prompt even with --output-only"),
			),
			withRelated(
				related("init", "creates or refreshes repository instruction scaffolding"),
				related("status", "reports Kit-managed refresh state before implementation"),
				related("loop prompt", "compiles a work-to-completion prompt from an existing SPEC.md or ad hoc intake"),
				related("loop workflow", "deprecated execution compatibility for V2 specs"),
			),
			withWhenToUse(
				"Use after or alongside native agent planning when material feature rationale needs durable repository memory.",
				"Use to adopt an existing spec without overwriting its workflow version.",
			),
			withWhenNotToUse(
				"Do not use as a standalone Git or GitHub delivery command; delivery mutations remain behind repo-local hard gates.",
				"Do not use the deprecated supervisor as the primary design or planning surface.",
			),
			withExamples("kit spec my-feature", "kit spec my-feature --legacy-supervisor"),
			withCaveats(
				"Kit does not ingest agent transcripts or copy proposed-plan markup automatically; the same-thread implementation agent semantically translates the accepted plan.",
				"Existing V2 specs require semantic curation before migration to V3.",
				"Native spec orientation reminds coding agents to run kit status and follow any Kit-managed refresh action before implementation; it does not run status automatically.",
			),
		),
		capability("notes", "Workflow", "Manage feature notes and local source-material scaffolds.", mutationWritesFiles, withFileWrites("creates docs/notes/<feature> with README.md, inbox, references, responses, and private scaffolding", "--add writes a timestamped note template with front matter", "private note contents are ignored by git while private/README.md and private/.gitignore stay tracked"), withFlags(flag("--add", "create a timestamped note template"), flag("--section", "choose inbox, references, responses, or private"), flag("--source", "set note front matter source, such as slack or manual"), flag("--status", "set note front matter status"), flag("--sensitivity", "set note front matter sensitivity"), flag("--private", "shortcut for --section=private and --sensitivity=private"), flag("--copy-path", "copy the feature notes directory path to the clipboard"), flag("--json", "emit machine-readable notes result")), withRelated(related("spec", "creates the regular feature notes scaffold for new feature specs"), related("map", "shows feature references that point at notes"), related("rules view feature-notes", "previews the ruleset for loading, referencing, and promoting notes"), related("scaffold spec", "creates SPEC.md and notes scaffolding without prompt output")), withWhenToUse("Use before or during feature work to capture Slack excerpts, customer context, screenshots, research links, draft responses, and other source material.", "Use private notes for local-only conversation history that should inform future work without entering git."), withWhenNotToUse("Do not treat notes as canonical requirements; promote durable decisions into SPEC.md, docs/CONSTITUTION.md, or another canonical project document.", "Do not store secrets, credentials, tokens, or private keys in notes, even under private/."), withExamples("kit notes", "kit notes my-feature", "kit notes my-feature --add --source slack --title \"Customer ask\"", "kit notes my-feature --add --private --title \"Slack conversation\""), withCaveats("Without a feature argument, the command opens an interactive selector for existing features or a new feature notes directory.", "Agents should load docs/references/rules/feature-notes.md when notes materially affect the task.", "Agents should ignore .gitkeep files and read only notes relevant to the current task.")),
		capability("loop", "Workflow", "Deprecated bare entrypoint for the V2 workflow loop; use explicit review and prompt subcommands.", mutationExecutesCommands, deprecated("Bare kit loop is retained temporarily for workflow_version 2 compatibility; use native planning or an explicit loop subcommand."), withFileWrites("can write loop state under .kit/loops"), withGitMutation("none", "delegated agent commands may mutate git independently"), withFlags(flag("--dry-run", "show V2 workflow loop plan without delegated execution", "read-only"), flag("--max-iterations", "bound V2 workflow loop execution")), withRelated(related("loop prompt", "creates feature-scoped or ad hoc work-to-completion prompts"), related("loop workflow", "deprecated V2 feature workflow loop"), related("loop review", "changed-code correctness review loop"), related("spec", "scaffolds living repository memory")), withExamples("kit loop prompt", "kit loop review", "kit loop workflow legacy-v2-feature"), withCaveats("V3 specs are rejected with native-planning guidance.", "The generated default Codex loop agent still pins --model gpt-5.6 during the V2 compatibility period; custom agent commands and model arguments are preserved.")),
		capability("loop prompt", "Workflow", "Create a work-to-completion loop prompt for a feature or ad hoc task.", mutationNone, withFileWrites("none; default output copies the generated prompt to the clipboard", "--output-only prints prompt text without writing files"), withGitMutation("none"), withFlags(flag("--output-only", "print the generated loop prompt instead of copying it", "read-only"), flag("--copy", "copy prompt even with --output-only")), withRelated(related("spec", "creates or resumes feature SPEC.md state"), related("loop workflow", "executes the v2 feature loop through a configured local agent"), related("loop review", "runs changed-code correctness review loops")), withWhenToUse("Use with a feature argument to generate a SPEC.md-scoped implementation loop prompt without running the loop agent.", "Use without a feature argument to answer a short interactive intake and generate an ad hoc loop-engineering prompt."), withWhenNotToUse("Do not use as the main `kit spec` flow; it compiles an implementation prompt from existing or ad hoc context.", "Do not use as a GitHub delivery command; issue, branch, commit, push, and PR mutation remain behind repo-local delivery gates."), withExamples("kit loop prompt", "kit loop prompt my-feature", "kit loop prompt my-feature --output-only"), withCaveats("Feature prompts require an existing SPEC.md; run `kit spec <feature>` first when the feature does not exist.", "Ad hoc prompts are flexible and do not create feature docs or persistent workflow state.")),
		capability("loop workflow", "Workflow", "Run the deprecated V2 feature workflow through a confidence-gated local agent loop.", mutationExecutesCommands, deprecated("Retained temporarily for workflow_version 2 compatibility; V3 uses native agent planning."), withFileWrites("writes stage-specific loop prompts, stdout, stderr, and run summaries under .kit/loops"), withGitMutation("none", "delegated agent commands may mutate files or git independently; Kit itself does not stage, commit, or push"), withFlags(flag("--dry-run", "show the next workflow stage without invoking the configured agent", "read-only"), flag("--until", "stop after a workflow stage is complete"), flag("--min-confidence", "override the required agent confidence percentage"), flag("--max-iterations", "bound loop execution"), flag("--json", "emit the loop report as JSON")), withRelated(related("loop review", "runs correctness review passes over changed code"), related("spec", "scaffolds V3 repository memory")), withExamples("kit loop workflow legacy-v2-feature --dry-run"), withCaveats("V3 specs are rejected with guidance to use native planning.", "V2 behavior remains available only during the compatibility period.")),
		capability(
			"loop review",
			"Workflow",
			"Run a coding-agent correctness review loop over changes not in the remote mainline.",
			mutationExecutesCommands,
			withNetwork("none by default", "--pr reads PR metadata, CodeRabbit checks, and unresolved non-outdated CodeRabbit review threads through gh"),
			withFileWrites("writes loop prompts, stdout, stderr, and run summaries under .kit/loops; delegated agent may edit local project files"),
			withGitMutation("none; command prompts explicitly forbid staging, commits, pushes, PR comments, and review-thread resolution"),
			withFlags(
				flag("--base", "override the comparison base; default is origin/main, then main"),
				flag("--pr", "opportunistically ingest CodeRabbit feedback from a pull request", "network read"),
				flag("--watch", "wait for CodeRabbit completion before finalizing PR-mode review", "network read with polling"),
				flag("--wait-for-coderabbit", "alias for --watch", "network read with polling"),
				flag("--dry-run", "show the first review prompt without invoking the configured agent", "read-only"),
				flag("--min-confidence", "override the required correctness percentage"),
				flag("--max-iterations", "bound review passes; default is 20"),
				flag("--subagents", "allow the parent review agent to pre-analyze changed-code lanes and choose subagents under agent-team-orchestration limits"),
				flag("--json", "emit the loop review report as JSON"),
			),
			withRelated(related("loop workflow", "runs the feature artifact workflow loop"), related("dispatch --loop", "PR prompt-prep alias and review-loop replacement")),
			withWhenToUse("Use before publishing or updating a PR when changed code should be locally reviewed and repaired until no high, medium, or correctness-impacting issues remain.", "Use with --pr when CodeRabbit feedback should be folded into local repair passes opportunistically."),
			withWhenNotToUse("Do not use when you only need a prompt from PR review threads; use `dispatch --loop --pr`.", "Do not use as a git/GitHub delivery command; it never stages, commits, pushes, comments, or resolves threads."),
			withExamples("kit loop review", "kit loop review --base origin/main", "kit loop review --pr 14", "kit loop review --pr 14 --wait-for-coderabbit"),
			withCaveats(
				"The correctness percentage is agent-reported and gated by the prompt plus validation evidence; it is not a mathematical proof.",
				"Review prompts use one agent by default; --subagents adds parent pre-analysis and shared subagent guidance when review lanes are clearly independent, with default max 3 and hard ceiling 4.",
				"The generated default Codex loop agent pins --model gpt-5.6 and uses --ignore-user-config so child runs use the reviewed model and avoid unrelated local MCP/plugin auth side effects.",
				"Human-readable runs stream emoji-marked runner progress and child-agent stdout/stderr to stderr; --json suppresses progress output so stdout stays machine-readable.",
				"Interactive terminals are prompted before rerunning after existing loop evidence or a max-iterations stop; JSON and dry-run modes do not prompt.",
				"Agent command setup failures stop immediately with stderr context instead of consuming every iteration.",
			),
		),
		capability("resume", "Workflow", "Resume the next useful Kit workflow action.", mutationNone, withRelated(related("status", "shows current feature state before resuming"))),
		capability("pause", "Workflow", "Mark or package feature work as paused.", mutationWritesFiles, withFileWrites("updates Kit workflow state for the paused feature"), withRelated(related("resume", "continues paused work"))),
		capability("complete", "Workflow", "Mark a feature as complete after validation.", mutationWritesFiles, withFileWrites("updates Kit feature state and progress artifacts"), withRelated(related("legacy verify", "runs staged checks before completion"), related("legacy reflect", "captures staged completion notes"), related("status", "reports Kit-managed refresh state before final delivery")), withCaveats("Successful completion reminds coding agents to run kit status and follow any Kit-managed refresh action before final delivery; it does not run status automatically.")),
		capability("project", "Workflow", "Run project-level Kit maintenance workflows.", mutationWritesFiles, withFileWrites("none by itself", "`project refresh --now` updates .kit.yaml cadence state"), withRelated(related("project refresh", "semantic Constitution refresh workflow"), related("reconcile", "structural Kit project refresh"))),
		capability("project refresh", "Workflow", "Generate or record semantic project documentation refresh work.", mutationWritesFiles, withNetwork("none"), withFileWrites("default prompt generation writes no project files and uses clipboard/output behavior", "--now writes project_refresh.constitution cadence state to .kit.yaml; docs/CONSTITUTION.md is never rewritten automatically"), withGitMutation("none"), withFlags(flag("--now", "mark the reviewed Constitution refresh complete in .kit.yaml"), flag("--constitution-only", "scope the generated prompt to docs/CONSTITUTION.md only"), flag("--output-only", "print the prompt instead of copying it", "read-only"), flag("--copy", "copy prompt even with --output-only")), withRelated(related("prompt project refresh", "prompt-library rendering path for the same default prompt"), related("check --project", "warns when the Constitution refresh cadence is overdue"), related("reconcile", "structural scaffold and registry refresh, not semantic Constitution learning")), withWhenToUse("Use after several completed features or whenever durable project rules, vocabulary, constraints, conventions, or workflow changes should be considered for docs/CONSTITUTION.md.", "Use `--now` only after a reviewed semantic refresh is complete."), withWhenNotToUse("Do not use as an automatic changelog or blind Constitution rewrite.", "Do not use instead of `kit reconcile --all --include-files` for structural scaffold, registry, or generated instruction-file refresh."), withExamples("kit project refresh", "kit project refresh --output-only", "kit project refresh --constitution-only --output-only", "kit project refresh --now"), withCaveats("Semantic documentation edits remain prompt-driven and reviewed; the command only generates guidance unless --now records cadence state.")),
		capability("rm", "Workflow", "Remove Kit-managed feature or state entries.", mutationDestructive, withFileWrites("removes or updates Kit-managed files depending on flags"), withAliases("remove"), withFlags(flag("--dry-run", "preview removals before changing files", "use before destructive cleanup")), withRelated(related("status", "inspect state before removal"))),
		capability("status", "Inspect & Repair", "Show current Kit project and feature status, including Kit-managed refresh state.", mutationNetwork, withNetwork("fetches the Kit ruleset registry with a 30s timeout to plan managed-file refresh drift", "if the registry is unavailable, status still renders local state and marks Kit-managed files as unchecked/unknown"), withFlags(flag("--json", "emit machine-readable status including kit_managed refresh fields"), flag("--all", "include all known features")), withRelated(related("map", "shows feature document graph"), related("check", "validates feature artifacts"), related("reconcile", "previews and applies managed-file, ruleset, and documentation reconciliation updates")), withCaveats("Registry fetch failures or deadline expiry do not abort status; inspect kit_managed.state=unknown and managed_files.unchecked before treating managed files as current.")),
		capability("registry", "Inspect & Repair", "Inspect Kit registry freshness.", mutationNetwork, withNetwork("none by itself", "`registry status` fetches the configured ruleset registry unless automated health management is explicitly disabled"), withFileWrites("none"), withGitMutation("none"), withRelated(related("registry status", "reports compact registry and managed-file freshness"), related("health", "applies safe managed updates and validates project health")), withWhenToUse("Use this command group to inspect the configured Kit registry."), withWhenNotToUse("Do not use it to apply updates; use `kit health`."), withExamples("kit registry status")),
		capability("registry status", "Inspect & Repair", "Show compact Kit registry and managed-file freshness.", mutationNetwork, withNetwork("fetches the configured Kit ruleset registry with a bounded timeout", "performs no network access when health.managed is explicitly false"), withFileWrites("none"), withGitMutation("none"), withFlags(flag("--json", "emit stable machine-readable freshness and opt-out state", "read-only")), withRelated(related("status", "shows the broader project and feature state"), related("health", "applies safe managed updates and validates the project")), withWhenToUse("Use in scheduled maintenance to decide whether a project needs Kit-managed updates."), withWhenNotToUse("Do not treat an unknown registry state as current or apply changes when health.managed=false."), withExamples("kit registry status", "kit registry status --json"), withCaveats("The planned count projects the complete Kit-managed refresh plan, including rules, instructions, configuration, and scaffold files.")),
		capability("health", "Inspect & Repair", "Apply safe Kit-managed updates and validate project health.", mutationWritesFiles, withNetwork("fetches the configured Kit ruleset registry with a bounded timeout", "performs no network access when health.managed is explicitly false"), withFileWrites("applies conflict-free Kit-managed rules, instructions, configuration, README, workflow, and scaffold updates", "--dry-run previews without writing; local customizations and conflicts are never force-overwritten"), withGitMutation("none"), withFlags(flag("--dry-run", "preview Kit health changes without writing files", "read-only"), flag("--diff", "print the planned unified diff; requires --dry-run", "read-only"), flag("--json", "emit stable machine-readable health results")), withRelated(related("registry status", "reports compact registry freshness before maintenance"), related("reconcile", "generates reviewed semantic curation guidance for unresolved drift"), related("check --project", "validates the project contract after managed updates")), withWhenToUse("Use for recurring Kit maintenance when safe managed updates should be applied by default and reviewed in a pull request."), withWhenNotToUse("Do not use as a Git, GitHub, or arbitrary product-code mutation command.", "Do not force-overwrite local customizations; follow the reported reconcile and curation action."), withExamples("kit health --dry-run --diff", "kit health", "kit health --json"), withCaveats("Omitted, null, or empty health configuration remains managed; only health.managed=false disables scheduled health maintenance.")),
		capability("map", "Inspect & Repair", "Show the artifact map for a feature.", mutationNone, withFlags(flag("--json", "emit machine-readable map output")), withRelated(related("check", "validates mapped artifacts"), related("capabilities", "explains command behavior"))),
		capability("capabilities", "Inspect & Repair", "List Kit commands and their safety behavior.", mutationNone, withFlags(flag("--json", "emit stable machine-readable capability data"), flag("--full", "include detailed hidden and deprecated records"), flag("--search", "filter visible command metadata")), withRelated(related("map", "shows feature context"), related("help", "shows command syntax")), withWhenToUse("Use before choosing a Kit command when command behavior, mutation, network, or file-write boundaries are uncertain.", "Inside the Kit source repository, use targeted lookup before implementing or extending a Kit command so the command catalog stays current."), withWhenNotToUse("Do not use as a replacement for `kit map` when the question is about feature documents or references.", "Do not use `--full` by default; prefer compact search or targeted lookup unless hidden/deprecated command metadata is needed.", "Do not maintain Kit's internal command catalog from a downstream project."), withExamples("kit capabilities --json", "kit capabilities dispatch --json", "kit capabilities --search loop --json"), withCaveats("Kit maintainers must keep this catalog current when command behavior changes; downstream projects should use it for discovery, not maintain it.")),
		capability("config", "Inspect & Repair", "Inspect and repair versioned Kit project configuration.", mutationWritesFiles, withNetwork("none by itself", "`config check` can list local AWS CLI profiles and, after interactive acceptance, call AWS STS to verify the selected account"), withFileWrites("none by itself", "interactive `config check` can update only schema_version and aws fields in .kit.yaml while preserving unknown fields; --json is read-only"), withGitMutation("none"), withRelated(related("config check", "validates .kit.yaml and offers safe inline repairs"), related("aws verify", "verifies configured AWS identity before AWS work")), withExamples("kit config check", "kit config check --json")),
		capability("config check", "Inspect & Repair", "Validate .kit.yaml schema and semantics and offer safe inline repairs.", mutationWritesFiles, withNetwork("none on the current complete fast path", "interactive AWS remediation runs `aws configure list-profiles` and calls STS only after the user accepts or selects a profile"), withFileWrites("interactive terminal runs can add the current schema_version and verified aws profile/account fields to .kit.yaml", "--json never prompts or writes"), withGitMutation("none"), withFlags(flag("--json", "emit a stable validation report without prompting or writing", "read-only")), withRelated(related("config", "configuration command group"), related("aws verify", "checks the configured AWS identity against .kit.yaml"), related("check --project", "validates the broader repository contract")), withWhenToUse("Use when .kit.yaml is missing current schema metadata, contains partial AWS context, or should be checked explicitly before other work."), withWhenNotToUse("Do not use to authenticate AWS or run aws sso login."), withExamples("kit config check", "kit config check --json"), withCaveats("Project-aware Kit commands perform the same local schema inspection automatically, but prompt only in an interactive terminal and avoid subprocesses on the complete fast path.")),
		capability("aws", "Inspect & Repair", "Verify the AWS context bound to the current Kit project.", mutationNetwork, withNetwork("none by itself", "`aws verify` calls AWS STS through the configured project profile"), withFileWrites("none"), withGitMutation("none"), withRelated(related("aws verify", "performs deterministic identity verification"), related("config check", "configures or repairs the project AWS binding")), withExamples("kit aws verify", "kit aws verify --json")),
		capability("aws verify", "Inspect & Repair", "Verify the configured AWS profile and account against .kit.yaml.", mutationNetwork, withNetwork("calls `aws sts get-caller-identity` with aws.profile from .kit.yaml"), withFileWrites("none"), withGitMutation("none"), withFlags(flag("--json", "emit the verified profile, account, and ARN as JSON", "read-only output; still calls STS")), withRelated(related("config check", "adds or repairs verified AWS config")), withWhenToUse("Run before the first AWS-dependent command in a task and immediately before AWS mutation."), withWhenNotToUse("Do not treat a profile name alone as proof of account identity."), withExamples("kit aws verify", "kit aws verify --json"), withCaveats("Fails when credentials are unavailable, AWS is disabled, config is incomplete, AWS_PROFILE conflicts with aws.profile, or the resolved account differs from aws.account_id.")),
		capability("check", "Inspect & Repair", "Validate Kit feature artifacts and workflow consistency.", mutationNone, withFlags(flag("--all", "check every feature"), flag("--project", "include project-level checks")), withRelated(related("map", "finds feature artifact inputs"), related("legacy verify", "runs staged implementation verification checks"))),
		capability("ci", "Inspect & Repair", "Inspect GitHub Actions CI state and prepare CI-fix prompts.", mutationNetwork, withNetwork("uses git/gh subprocesses and GitHub CLI/API to inspect PR checks and logs", "--dispatch can ask GitHub to rerun eligible workflows; --copilot can attempt Copilot-assisted diagnosis"), withFileWrites("can update .kit.yaml default branch cache", "prompt output flags can copy or write generated text"), withFlags(flag("--pr", "select a pull request to inspect"), flag("--run", "inspect one workflow run"), flag("--dispatch", "rerun eligible workflows", "network mutation"), flag("--copilot", "attempt Copilot-assisted diagnosis when supported", "optional network/tooling behavior"), flag("--no-copilot", "disable Copilot-assisted diagnosis"), flag("--json", "emit machine-readable CI summary")), withRelated(related("legacy verify", "runs local validation"), related("dispatch", "routes review or CI prompts")), withExamples("kit ci", "kit ci --pr 14 --json", "kit ci --run 123456789 --dispatch"), withCaveats("Default diagnosis is read-oriented, but `--dispatch` can rerun eligible workflows and must be treated as a network mutation.")),
		capability("pr", "Inspect & Repair", "Run pull-request repair workflows.", mutationNetwork, withNetwork("none by itself", "`pr fix` can list open pull requests and fetch unresolved review threads through gh"), withFileWrites("none by itself", "`pr fix` opens the editor and can copy generated prompt output outside project files"), withGitMutation("none; GitHub delivery remains a separate repo-local gate"), withRelated(related("pr fix", "selects or targets a PR and prepares a dispatch prompt from human and CodeRabbit feedback"), related("loop review", "lower-level changed-code review loop"), related("dispatch", "lower-level prompt-prep and review-thread resolution utility")), withWhenToUse("Use when choosing a pull-request repair workflow under Kit's PR review tooling."), withWhenNotToUse("Do not use as a GitHub delivery command; staging, commits, pushes, and PR comments remain explicit separate steps."), withExamples("kit pr fix", "kit pr fix --pr 14")),
		capability(
			"pr fix",
			"Inspect & Repair",
			"Select or target a pull request and prepare a dispatch prompt from review feedback.",
			mutationNetwork,
			withNetwork("uses gh pr list when --pr is omitted", "--pr reads unresolved non-outdated human and CodeRabbit review threads through gh api graphql"),
			withFileWrites("none to project files; opens the editor and can copy generated prompt output outside project files"),
			withGitMutation("none; generated prompt keeps staging, commits, pushes, PR comments, and review-thread resolution as separate explicit steps"),
			withFlags(
				flag("--pr", "target a PR URL, Markdown link, owner/repo#number, or current-repo number", "network read"),
				flag("--coderabbit", "include only CodeRabbit-authored review comments"),
				flag("--editor", "open review tasks in a specific editor command"),
				flag("--vim", "open review tasks in a vim-compatible editor"),
				flag("--copy", "copy generated prompt output even with --output-only"),
				flag("--output-only", "print prompt text instead of copying it", "read-only"),
				flag("--max-subagents", "bound the generated dispatch queue; default 3, hard ceiling 4"),
			),
			withRelated(related("dispatch", "lower-level PR review-thread prompt intake and explicit thread resolution"), related("loop review", "lower-level changed-code review loop"), related("ci", "diagnoses GitHub Actions failures")),
			withWhenToUse("Use as the default PR review repair entrypoint when human or CodeRabbit feedback should be turned into an editable dispatch prompt.", "Run without --pr to select from open pull requests in the current repository, or pass --pr for URL/number targeting."),
			withWhenNotToUse("Do not use as the publishing step after fixes; follow the repo-local GitHub delivery gate for staging, committing, pushing, and PR comments.", "Do not use as the review-thread resolution step; use `kit dispatch --pr <target> --resolve --yes` only after fixes or no-op decisions are complete."),
			withExamples("kit pr fix", "kit pr fix --pr 14", "kit pr fix --pr https://github.com/jamesonstone/kit/pull/6", "kit pr fix --pr 14 --output-only"),
			withCaveats("This command is an ergonomic wrapper around the prompt-producing `kit dispatch --pr` path; it does not run the loop agent or edit local files.", "The generated prompt uses Agent Team Plan structure and caps concurrent subagents at 3 by default, 4 maximum.", "The generated prompt requires post-push reflection before review-thread resolution.", "Resolve only current review threads verified as fixed or intentionally no-op using `kit dispatch --pr <target> --resolve --yes`."),
		),
		capability("trace", "Inspect & Repair", "Trace Kit artifact relationships for a feature.", mutationNone, withRelated(related("map", "shows the feature artifact graph"))),
		capability("replay", "Inspect & Repair", "Replay recorded Kit verification or workflow context.", mutationExecutesCommands, withFileWrites("can write replay output or run artifacts"), withFlags(flag("--dry-run", "preview replay plan when supported", "prefer before executing")), withRelated(related("legacy verify", "creates verification run context"))),
		capability("state", "Inspect & Repair", "Inspect or refresh Kit project state.", mutationWritesFiles, withFileWrites("default inspection is read-only", "the refresh action updates Kit state files"), withFlags(flag("--json", "emit machine-readable state output")), withRelated(related("status", "renders state for humans"))),
		capability("eval", "Inspect & Repair", "Evaluate Kit project quality signals.", mutationNone, withFlags(flag("--json", "emit machine-readable evaluation output")), withRelated(related("check", "validates feature artifacts"), related("legacy verify", "runs task verification"))),
		capability("improve", "Inspect & Repair", "Run deterministic Kit harness benchmarks and improvement evidence workflows.", mutationExecutesCommands, withFileWrites("writes local run artifacts under .kit/improve/runs and updates .kit/improve/latest", "subcommands that package reports write report, candidate, prompt, and scorecard artifacts under .kit/improve; --dry-run on run avoids writes"), withGitMutation("none; PR creation remains behind repo-local GitHub delivery gates"), withFlags(flag("--json", "emit machine-readable command output")), withRelated(related("eval", "runs smaller built-in harness checks"), related("loop review", "repairs changed code with an agent loop"), related("capabilities", "documents command behavior")), withWhenToUse("Use when improving Kit's own harness through repeatable fixture tasks, output assertions, provenance hashes, traces, weakness mining, and reviewable evidence."), withWhenNotToUse("Do not use as a hidden autonomous merger, model trainer, or downstream product-code repair command.", "Do not infer live model quality, cost, latency, turns, or routing from deterministic suites that make no model calls.", "Do not use to bypass GitHub delivery rules; issue, branch, commit, push, and PR mutation stay behind repo-local hard gates."), withExamples("kit improve", "kit improve run --suite default --json", "kit improve run --suite prompt-system --kit-binary /path/to/kit --json", "kit improve mine --from .kit/improve/latest --json"), withCaveats("The default suite is a capability smoke test; prompt-system renders representative prompt surfaces three times.", "Candidate proposal generation is deterministic metadata/prompt packaging and does not embed a model runtime.", "Generated traces are local artifacts and should be redacted/reviewed before upload.")),
		capability("improve run", "Inspect & Repair", "Run a deterministic Kit benchmark suite in disposable fixture workspaces.", mutationExecutesCommands, withFileWrites("writes .kit/improve/runs/<id>/run.json, traces, command output excerpts, and disposable workspace copies", "--dry-run avoids artifact writes"), withFlags(flag("--suite", "select benchmark suite; default is capability smoke, prompt-system renders prompts"), flag("--kit-binary", "evaluate a specific Kit executable and record its SHA-256"), flag("--dry-run", "plan the run without writing artifacts", "read-only"), flag("--json", "emit run manifest JSON")), withRelated(related("improve mine", "clusters failed traces"), related("improve report", "renders run evidence")), withExamples("kit improve run --suite default", "kit improve run --suite prompt-system --kit-binary /tmp/baseline-kit --json"), withCaveats("A nonzero command, failed assertion, or allowed-surface violation fails the manifest and command exit status.", "Run manifests record runner/binary/suite hashes, assertion completeness, output size, local command duration, and repeated-output determinism.", "Stdout trace metrics and hashes describe the exact persisted redacted, workspace-normalized, 200-line excerpt rather than raw command output.")),
		capability("improve mine", "Inspect & Repair", "Mine Kit improvement traces for weakness clusters.", mutationWritesFiles, withFileWrites("writes weakness-report.json under the selected .kit/improve artifact directory"), withFlags(flag("--from", "artifact directory to read; defaults to .kit/improve/latest"), flag("--json", "emit weakness report JSON")), withRelated(related("improve run", "produces traces"), related("improve propose", "generates candidate prompts")), withExamples("kit improve mine --from .kit/improve/latest --json")),
		capability("improve propose", "Inspect & Repair", "Generate bounded candidate prompts from weakness clusters.", mutationWritesFiles, withFileWrites("writes candidate metadata and prompt artifacts under .kit/improve/runs/<id>/candidates"), withFlags(flag("--from", "artifact directory to read; defaults to .kit/improve/latest"), flag("--max-candidates", "maximum candidate count; default 3"), flag("--json", "emit candidate metadata JSON")), withRelated(related("improve mine", "produces weakness clusters"), related("dispatch", "turns prompts into agent work plans")), withExamples("kit improve propose --from .kit/improve/latest --max-candidates 3 --json")),
		capability("improve validate", "Inspect & Repair", "Validate Kit improvement candidate metadata; this is not a behavioral score.", mutationNone, withFlags(flag("--candidate", "candidate JSON path; required"), flag("--json", "emit scorecard JSON")), withRelated(related("improve propose", "writes candidate metadata"), related("improve run", "provides behavioral fixture evidence"), related("improve report", "summarizes evidence")), withExamples("kit improve validate --candidate .kit/improve/latest/candidates/candidate-001/candidate.json --json"), withCaveats("A well-formed proposed candidate returns acceptance=metadata-only and score=0; compare identical improve run suites separately.")),
		capability("improve report", "Inspect & Repair", "Render a Markdown report from Kit improvement run artifacts.", mutationWritesFiles, withFileWrites("writes report.md under the selected .kit/improve artifact directory"), withFlags(flag("--from", "artifact directory to read; defaults to .kit/improve/latest"), flag("--json", "emit report markdown in JSON")), withRelated(related("improve run", "produces run manifest"), related("improve pr", "packages PR body content")), withExamples("kit improve report --from .kit/improve/latest")),
		capability("improve pr", "Inspect & Repair", "Prepare a PR body for Kit improvement evidence without bypassing delivery gates.", mutationWritesFiles, withFileWrites("reads/writes report artifacts and prints a PR body", "--create-pr intentionally stops and requires repo-local GitHub delivery workflow"), withGitMutation("none; --create-pr returns a gate error instead of mutating GitHub"), withFlags(flag("--from", "artifact directory to read; defaults to .kit/improve/latest"), flag("--issue", "issue reference for the Ticket section"), flag("--create-pr", "stop and require repo-local GitHub delivery workflow before PR mutation", "GitHub delivery hard gate"), flag("--json", "emit PR body JSON")), withRelated(related("github-pr-delivery", "repo-local delivery rules"), related("improve report", "generates evidence summary")), withExamples("kit improve pr --from .kit/improve/latest --issue '#46'", "kit improve pr --from .kit/improve/latest --issue '#46' --json"), withCaveats("Use the generated body inside the normal issue-number branch, explicit staging, commit, push, and ready PR workflow.")),
		capability("rules", "Inspect & Repair", "Manage Kit rule bindings and inspect available rules.", mutationWritesFiles, withFileWrites("root is mostly dispatch; add and link write rule files or feature links"), withAliases("rule"), withRelated(related("rules list", "lists available rules"), related("rules add", "adds rules to the project"))),
		capability("rules add", "Inspect & Repair", "Add a rule to the project rule set.", mutationWritesFiles, withFileWrites("writes rule files or rule references under docs/references/rules"), withFlags(flag("--force", "replace existing rule content when supported", "review current rule first")), withRelated(related("rules list", "find rules that can be added"), related("rules view", "inspect a rule before adding"))),
		capability("rules list", "Inspect & Repair", "List available or installed Kit rules.", mutationNone, withRelated(related("rules add", "adds one listed rule"))),
		capability("rules view", "Inspect & Repair", "Show the content or metadata for a Kit rule.", mutationNone, withRelated(related("rules add", "adds a viewed rule"))),
		capability("rules link", "Inspect & Repair", "Link a rule to a feature or artifact.", mutationWritesFiles, withFileWrites("updates feature docs or rule references to record the link"), withRelated(related("rules view", "review the rule first"), related("map", "shows feature artifact context"))),
		capability(
			"reconcile",
			"Inspect & Repair",
			"Reconcile Kit-managed project files, rules, and documentation drift.",
			mutationWritesFiles,
			withNetwork("fetches the Kit ruleset registry when managed files are included"),
			withFileWrites("without --include-files, default and prompt-only reconciliation emit a coding-agent prompt and do not write files", "--include-files applies Kit-managed file, ruleset, README, config, init scaffold, and instruction refreshes; --dry-run previews them without writing files"),
			withGitMutation("none"),
			withFlags(
				flag("--include-files", "include Kit-managed file and ruleset refreshes before auditing docs"),
				flag("--all", "make whole-project reconcile explicit; combine with --include-files for scaffold refreshes"),
				flag("--force", "force included Kit-managed file and ruleset refreshes", "review local edits first"),
				flag("--dry-run", "preview included file refreshes without writing files", "read-only"),
				flag("--diff", "print planned included file refreshes as a unified diff with --dry-run", "read-only"),
				flag("--file", "limit included refresh to one Kit-managed file; repeat for multiple files"),
				flag("--output-only", "print prompt text or refresh preview to stdout instead of copying"),
				flag("--copy", "copy prompt even with --output-only"),
				flag("--migrate-references", "include instructions for migrating deprecated front matter dependencies to references"),
				flag("--migrate-verification", "include advisory instructions for adding executable verification fields to active tasks"),
			),
			withRelated(
				related("status", "reports whether managed-file refresh or attention is needed"),
				related("check", "validates known invariants"),
				related("init --refresh", "lower-level compatibility path used by reconcile for managed-file refreshes"),
				related("project refresh", "semantic Constitution refresh after structural reconcile is clean"),
			),
			withWhenToUse(
				"Use as the reviewed surface for bringing a Kit-managed project up to date with current files, rules, and scaffold behavior.",
				"Run interactively to answer include files?, force these changes?, and output coding-agent prompt too?",
				"Use `--include-files --dry-run --diff` to preview structural refreshes before applying them.",
			),
			withWhenNotToUse(
				"Do not use as a GitHub delivery command; it does not stage, commit, push, or open PRs.",
				"Do not choose force until local generated-doc, ruleset, or workflow edits have been reviewed.",
			),
			withExamples("kit reconcile", "kit reconcile --all --include-files", "kit reconcile --include-files --dry-run --diff", "kit reconcile --include-files", "kit reconcile --include-files --force", "kit reconcile --output-only"),
		),
		capability(
			"instructions",
			"Prompt Utilities",
			"Print versioned provider-neutral coding-agent instructions as raw Markdown.",
			mutationNone,
			withFlags(flag("--version", "select an exact immutable vN version; defaults to the current version", "read-only")),
			withRelated(
				related("prompt", "renders reusable task-specific and compatibility prompts"),
				related("scaffold agents", "writes repository-specific agent instruction files"),
			),
			withWhenToUse(
				"Use when adding Kit's shared system-level coding-agent policy directly to Codex, Claude, or GitHub Copilot.",
				"Omit --version for the current policy or pass --version=vN to reproduce an earlier release.",
			),
			withWhenNotToUse(
				"Do not use to create or refresh repository-specific AGENTS.md, CLAUDE.md, or Copilot files; use `kit scaffold agents`.",
				"Do not use for a task-specific reusable prompt; use `kit prompt`.",
			),
			withExamples("kit instructions", "kit instructions --version=v3", "kit instructions --version=v2"),
			withCaveats(
				"The command writes only raw Markdown to stdout and never copies to the clipboard.",
				"All versions are embedded in the installed binary; selection performs no network or project configuration access.",
			),
		),
		capability("prompt", "Prompt Utilities", "Work with Kit prompt templates.", mutationNone, withFlags(flag("--output-only", "print prompt text instead of copying it with metadata"), flag("--copy", "copy prompt even with --output-only")), withRelated(related("prompt list", "lists available prompts, including the legacy V2 supervisor entry"), related("spec", "scaffolds or adopts living repository memory"), related("set prompt", "sets prompt preferences")), withWhenToUse("Use to render reusable support and compatibility prompts.", "Use this catalog entry when looking for the former kit spec prompt behavior."), withExamples("kit prompt list", "kit prompt kit spec", "kit prompt workflow spec --output-only"), withCaveats("`kit prompt kit spec` is legacy V2 compatibility; plain `kit spec <feature>` uses native-planning orientation.")),
		capability("prompt list", "Prompt Utilities", "List available Kit prompt templates, including the legacy V2 supervisor entry.", mutationNone, withRelated(related("prompt", "renders prompt templates"), related("spec", "creates or adopts SPEC.md when durable memory is needed")), withExamples("kit prompt list")),
		capability("set", "Prompt Utilities", "Update Kit configuration values.", mutationWritesFiles, withFileWrites("writes Kit local or global configuration"), withRelated(related("set prompt", "sets prompt-related configuration"))),
		capability("set prompt", "Prompt Utilities", "Set the active prompt preference.", mutationWritesFiles, withFileWrites("writes Kit prompt configuration"), withRelated(related("prompt list", "find prompt names before setting one"))),
		capability("handoff", "Prompt Utilities", "Generate handoff context for continuing work.", mutationNone, withRelated(related("summarize", "condenses project or feature context"))),
		capability("summarize", "Prompt Utilities", "Summarize Kit project or feature context.", mutationNone, withRelated(related("handoff", "packages summary for a continuation"))),
		capability("dispatch", "Prompt Utilities", "Build Agent Team Plan prompts for agents, PR review threads, and CodeRabbit prompt-prep intake.", mutationNetwork, withNetwork("none by default", "--pr fetches unresolved, non-outdated GitHub PR review threads through gh api graphql; --loop also reads PR metadata and optional CodeRabbit check status; --resolve --yes mutates GitHub review-thread state"), withFileWrites("none by default", "editor, --copy, and output flags can copy or write generated prompt output outside project files"), withGitMutation("none"), withFlags(flag("--pr", "prefill the dispatch editor from unresolved, non-outdated PR review threads", "network read"), flag("--loop", "route PR review feedback through the prompt-prep review-loop workflow"), flag("--coderabbit", "with --pr, keep CodeRabbit-authored comments and extract Prompt for AI Agents blocks"), flag("--resolve", "with --pr, resolve matching unresolved review threads after fixes or no-op decisions are complete", "GitHub mutation; requires --yes"), flag("--yes", "confirm --resolve after fixes or no-op decisions are complete", "required for mutation"), flag("--watch", "with --loop, wait for current-head CodeRabbit review completion", "network read with polling"), flag("--copy", "copy generated prompt output"), flag("--output-only", "print prompt without wrapper text"), flag("--max-subagents", "bound the generated dispatch queue; default 3, hard ceiling 4")), withRelated(related("loop review", "coding-agent correctness repair loop"), related("ci", "inspects CI context"), related("code-review", "builds review-focused prompts")), withExamples("kit dispatch --file tasks.md", "kit dispatch --pr 14 --coderabbit", "kit dispatch --loop --pr 14 --watch", "kit dispatch --pr 14 --resolve --yes"), withCaveats("Default dispatch generates prompts only; `--resolve --yes` is the explicit GitHub mutation path for already-handled review threads.", "Generated dispatch prompts require one accountable supervisor, an Agent Team Plan before subagent execution, default max 3 concurrent subagents, and hard ceiling 4.")),
		capability("code-review", "Prompt Utilities", "Generate a read-only, finding-oriented review prompt for the current branch change set.", mutationNone, withRelated(related("dispatch", "routes prompts to specialized agents"), related("legacy verify", "runs executable checks")), withCaveats("The prompt reports only evidence-backed actionable findings in severity order and does not add generic subagent implementation guidance.")),
		capability("skill", "Prompt Utilities", "Inspect or generate Kit skill prompts.", mutationNone, withRelated(related("skill mine", "mines local context for skill material"))),
		capability("skill mine", "Prompt Utilities", "Mine repository context for reusable skill material.", mutationNone, withFileWrites("none by default", "shared editor flags can copy or write generated prompt output"), withFlags(flag("--copy", "copy generated prompt output"), flag("--output-only", "print prompt without wrapper text")), withRelated(related("skill", "skill command group"))),
		capability("upgrade", "Utilities", "Upgrade the Kit CLI installation.", mutationNetwork, withNetwork("downloads release metadata or binaries"), withFileWrites("writes the installed Kit binary or related install files"), withFlags(flag("--check", "check for an upgrade without installing when supported", "prefer for read-only inspection")), withRelated(related("version", "shows current installed version"))),
		capability("version", "Utilities", "Print the Kit CLI version.", mutationNone, withRelated(related("upgrade", "updates the installed version"))),
		capability("completion", "Utilities", "Generate shell completion scripts.", mutationNone, withFileWrites("none by default", "the shell may redirect output to a completion file outside Kit"), withRelated(related("help", "shows command syntax"))),
		capability(
			"git wt path",
			"Utilities",
			"Print the exact registered worktree path for a lane.",
			mutationNone,
			withGitMutation("none; reads registered worktree metadata only"),
			withWhenToUse(
				"Use in shell command substitution to navigate to an existing lane.",
				"Use when scripts need the canonical path of an exact registered lane.",
			),
			withWhenNotToUse(
				"Do not expect an external command to change the parent shell's directory.",
				"Do not use for fuzzy lane discovery; use `git wt list` to inspect registered worktrees.",
			),
			withExamples(`cd "$(git wt path GH-101)"`, `git -C "$(git wt path GH-101)" status`),
			withCaveats("The command is read-only and rejects unregistered lanes or traversal instead of guessing."),
		),
		capability("help", "Utilities", "Show command help and flag syntax.", mutationNone, withRelated(related("capabilities", "adds behavior and safety metadata"))),
	}

	sort.SliceStable(records, func(i, j int) bool {
		return lessCapabilityRecord(records[i], records[j])
	})
	return records
}
