package cli

func workflowCapabilityRecords() []capabilityRecord {
	return []capabilityRecord{
		capability("backlog", "Workflow", "Inspect and manage feature backlog entries.", mutationWritesFiles, withFileWrites("can update backlog state depending on subcommand and flags"), withRelated(related("resume", "selects paused or pending work"))),
		capability("legacy", "Workflow", "List deprecated v1 staged workflow commands retained for migration.", mutationNone, withRelated(related("spec", "scaffolds living repository memory around native planning")), withWhenToUse("Use when finishing existing BRAINSTORM.md / PLAN.md / TASKS.md staged work."), withWhenNotToUse("Do not use for new work; use native planning and `kit spec <feature>` only when material rationale needs persistence.")),
		capability(
			"spec",
			"Workflow",
			"Scaffold or orient a living specification for native agent planning.",
			mutationWritesFiles,
			withFileWrites(
				"writes docs/specs/<feature>/SPEC.md for workflow_version 3 when no spec exists",
				"preserves existing V1 and V2 specifications without mechanical migration",
				"creates feature notes/reference-material directories",
				"updates PROJECT_PROGRESS_SUMMARY.md and prints concise native-planning orientation",
				"--legacy-supervisor and former supervisor-only flags retain deprecated V2 behavior",
			),
			withFlags(
				flag("--legacy-supervisor", "run the deprecated V2 lifecycle supervisor"),
				flag("--prompt-only", "emit the v2 supervisor prompt for an existing feature without writing adoption changes or prompting", "read-only"),
				flag("--revise-thesis", "append a dated thesis note and refresh delivery intent before rendering the prompt"),
				flag("--output-only", "print the prompt instead of copying it"),
				flag("--copy", "copy prompt even with --output-only"),
			),
			withRelated(
				related("init", "creates or refreshes repository instruction scaffolding"),
				related("status", "reports Kit-managed refresh state before implementation"),
				related("loop prompt", "compiles a work-to-completion prompt from an existing SPEC.md or ad hoc intake"),
				related("loop workflow", "deprecated execution compatibility for V2 specs"),
			),
			withWhenToUse(
				"Use after or alongside native agent planning when material feature rationale needs durable repository memory.",
				"Use to adopt an existing spec without overwriting its workflow version.",
			),
			withWhenNotToUse(
				"Do not use as a standalone Git or GitHub delivery command; delivery mutations remain behind repo-local hard gates.",
				"Do not use the deprecated supervisor as the primary design or planning surface.",
			),
			withExamples("kit spec my-feature", "kit spec my-feature --legacy-supervisor"),
			withCaveats(
				"Kit does not ingest agent transcripts or copy proposed-plan markup automatically; the same-thread implementation agent semantically translates the accepted plan.",
				"Existing V2 specs require semantic curation before migration to V3.",
				"Native spec orientation reminds coding agents to run kit status and follow any Kit-managed refresh action before implementation; it does not run status automatically.",
			),
		),
		capability("notes", "Workflow", "Manage feature notes and local source-material scaffolds.", mutationWritesFiles, withFileWrites("creates docs/notes/<feature> with README.md, inbox, references, responses, and private scaffolding", "--add writes a timestamped note template with front matter", "private note contents are ignored by git while private/README.md and private/.gitignore stay tracked"), withFlags(flag("--add", "create a timestamped note template"), flag("--section", "choose inbox, references, responses, or private"), flag("--source", "set note front matter source, such as slack or manual"), flag("--status", "set note front matter status"), flag("--sensitivity", "set note front matter sensitivity"), flag("--private", "shortcut for --section=private and --sensitivity=private"), flag("--copy-path", "copy the feature notes directory path to the clipboard"), flag("--json", "emit machine-readable notes result")), withRelated(related("spec", "creates the regular feature notes scaffold for new feature specs"), related("map", "shows feature references that point at notes"), related("rules view feature-notes", "previews the ruleset for loading, referencing, and promoting notes"), related("scaffold spec", "creates SPEC.md and notes scaffolding without prompt output")), withWhenToUse("Use before or during feature work to capture Slack excerpts, customer context, screenshots, research links, draft responses, and other source material.", "Use private notes for local-only conversation history that should inform future work without entering git."), withWhenNotToUse("Do not treat notes as canonical requirements; promote durable decisions into SPEC.md, docs/CONSTITUTION.md, or another canonical project document.", "Do not store secrets, credentials, tokens, or private keys in notes, even under private/."), withExamples("kit notes", "kit notes my-feature", "kit notes my-feature --add --source slack --title \"Customer ask\"", "kit notes my-feature --add --private --title \"Slack conversation\""), withCaveats("Without a feature argument, the command opens an interactive selector for existing features or a new feature notes directory.", "Agents should load docs/references/rules/feature-notes.md when notes materially affect the task.", "Agents should ignore .gitkeep files and read only notes relevant to the current task.")),
		capability("loop", "Workflow", "Deprecated bare entrypoint for the V2 workflow loop; use explicit review and prompt subcommands.", mutationExecutesCommands, deprecated("Bare kit loop is retained temporarily for workflow_version 2 compatibility; use native planning or an explicit loop subcommand."), withFileWrites("can write loop state under .kit/loops"), withGitMutation("none", "delegated agent commands may mutate git independently"), withFlags(flag("--dry-run", "show V2 workflow loop plan without delegated execution", "read-only"), flag("--max-iterations", "bound V2 workflow loop execution")), withRelated(related("loop prompt", "creates feature-scoped or ad hoc work-to-completion prompts"), related("loop workflow", "deprecated V2 feature workflow loop"), related("loop review", "changed-code correctness review loop"), related("spec", "scaffolds living repository memory")), withExamples("kit loop prompt", "kit loop review", "kit loop workflow legacy-v2-feature"), withCaveats("V3 specs are rejected with native-planning guidance.", "The generated default Codex loop agent still pins --model gpt-5.6 during the V2 compatibility period; custom agent commands and model arguments are preserved.")),
		capability("loop prompt", "Workflow", "Create a work-to-completion loop prompt for a feature or ad hoc task.", mutationNone, withFileWrites("none; default output copies the generated prompt to the clipboard", "--output-only prints prompt text without writing files"), withGitMutation("none"), withFlags(flag("--output-only", "print the generated loop prompt instead of copying it", "read-only"), flag("--copy", "copy prompt even with --output-only")), withRelated(related("spec", "creates or resumes feature SPEC.md state"), related("loop workflow", "executes the v2 feature loop through a configured local agent"), related("loop review", "runs changed-code correctness review loops")), withWhenToUse("Use with a feature argument to generate a SPEC.md-scoped implementation loop prompt without running the loop agent.", "Use without a feature argument to answer a short interactive intake and generate an ad hoc loop-engineering prompt."), withWhenNotToUse("Do not use as the main `kit spec` flow; it compiles an implementation prompt from existing or ad hoc context.", "Do not use as a GitHub delivery command; issue, branch, commit, push, and PR mutation remain behind repo-local delivery gates."), withExamples("kit loop prompt", "kit loop prompt my-feature", "kit loop prompt my-feature --output-only"), withCaveats("Feature prompts require an existing SPEC.md; run `kit spec <feature>` first when the feature does not exist.", "Ad hoc prompts are flexible and do not create feature docs or persistent workflow state.")),
		capability("loop workflow", "Workflow", "Run the deprecated V2 feature workflow through a confidence-gated local agent loop.", mutationExecutesCommands, deprecated("Retained temporarily for workflow_version 2 compatibility; V3 uses native agent planning."), withFileWrites("writes stage-specific loop prompts, stdout, stderr, and run summaries under .kit/loops"), withGitMutation("none", "delegated agent commands may mutate files or git independently; Kit itself does not stage, commit, or push"), withFlags(flag("--dry-run", "show the next workflow stage without invoking the configured agent", "read-only"), flag("--until", "stop after a workflow stage is complete"), flag("--min-confidence", "override the required agent confidence percentage"), flag("--max-iterations", "bound loop execution"), flag("--json", "emit the loop report as JSON")), withRelated(related("loop review", "runs correctness review passes over changed code"), related("spec", "scaffolds V3 repository memory")), withExamples("kit loop workflow legacy-v2-feature --dry-run"), withCaveats("V3 specs are rejected with guidance to use native planning.", "V2 behavior remains available only during the compatibility period.")),
		capability(
			"loop review",
			"Workflow",
			"Run a coding-agent correctness review loop over changes not in the remote mainline.",
			mutationExecutesCommands,
			withNetwork("none by default", "--pr reads PR metadata and review feedback through gh and fetches origin while resolving the writable PR head"),
			withFileWrites("writes loop prompts, stdout, stderr, and run summaries under .kit/loops; delegated agent may edit local project files", "--pr may create the canonical PR-head worktree and link the primary checkout's exact .env"),
			withGitMutation("none without --pr", "--pr may fetch origin and add or attach the exact PR-head worktree; it never stages, commits, pushes, comments, or resolves threads"),
			withFlags(
				flag("--base", "override the comparison base; default is origin/main, then main"),
				flag("--pr", "resolve the exact writable PR-head worktree and opportunistically ingest CodeRabbit feedback", "conditional worktree creation; prompts before including dirty changes"),
				flag("--watch", "wait for CodeRabbit completion before finalizing PR-mode review", "network read with polling"),
				flag("--wait-for-coderabbit", "alias for --watch", "network read with polling"),
				flag("--dry-run", "show the first review prompt without invoking the configured agent", "with --pr, exact worktree preparation can still occur"),
				flag("--min-confidence", "override the required correctness percentage"),
				flag("--max-iterations", "bound review passes; default is 20"),
				flag("--subagents", "allow the parent review agent to pre-analyze changed-code lanes and choose subagents under agent-team-orchestration limits"),
				flag("--json", "emit the loop review report as JSON"),
			),
			withRelated(related("loop workflow", "runs the feature artifact workflow loop"), related("dispatch --loop", "PR prompt-prep alias and review-loop replacement")),
			withWhenToUse("Use before publishing or updating a PR when changed code should be locally reviewed and repaired until no high, medium, or correctness-impacting issues remain.", "Use with --pr when CodeRabbit feedback should be folded into local repair passes opportunistically."),
			withWhenNotToUse("Do not use when you only need a prompt from PR review threads; use `dispatch --loop --pr`.", "Do not use as a git/GitHub delivery command; it never stages, commits, pushes, comments, or resolves threads."),
			withExamples("kit loop review", "kit loop review --base origin/main", "kit loop review --pr 14", "kit loop review --pr 14 --wait-for-coderabbit"),
			withCaveats(
				"PR mode refuses forks, resolves a canonical PR URL and push target, and runs the configured agent from the exact writable PR-head worktree.",
				"If that worktree is dirty, Kit asks whether to include the existing changes and carries the answer into every repair prompt.",
				"The correctness percentage is agent-reported and gated by the prompt plus validation evidence; it is not a mathematical proof.",
				"Review prompts use one agent by default; --subagents adds parent pre-analysis and shared subagent guidance when review lanes are clearly independent, with default max 3 and hard ceiling 4.",
				"The generated default Codex loop agent pins --model gpt-5.6 and uses --ignore-user-config so child runs use the reviewed model and avoid unrelated local MCP/plugin auth side effects.",
				"Human-readable runs stream emoji-marked runner progress and child-agent stdout/stderr to stderr; --json suppresses progress output so stdout stays machine-readable.",
				"Interactive terminals are prompted before rerunning after existing loop evidence or a max-iterations stop; JSON and dry-run modes do not prompt.",
				"Agent command setup failures stop immediately with stderr context instead of consuming every iteration.",
			),
		),
		capability("resume", "Workflow", "Resume the next useful Kit workflow action.", mutationNone, withRelated(related("status", "shows current feature state before resuming"))),
		capability("pause", "Workflow", "Mark or package feature work as paused.", mutationWritesFiles, withFileWrites("updates Kit workflow state for the paused feature"), withRelated(related("resume", "continues paused work"))),
		capability("complete", "Workflow", "Mark a feature as complete after validation.", mutationWritesFiles, withFileWrites("updates Kit feature state and progress artifacts"), withRelated(related("legacy verify", "runs staged checks before completion"), related("legacy reflect", "captures staged completion notes"), related("status", "reports Kit-managed refresh state before final delivery")), withCaveats("Successful completion reminds coding agents to run kit status and follow any Kit-managed refresh action before final delivery; it does not run status automatically.")),
		capability("project", "Workflow", "Run project-level Kit maintenance workflows.", mutationWritesFiles, withFileWrites("none by itself", "`project refresh --now` updates .kit.yaml cadence state"), withRelated(related("project refresh", "semantic Constitution refresh workflow"), related("reconcile", "structural Kit project refresh"))),
		capability("project refresh", "Workflow", "Generate or record semantic project documentation refresh work.", mutationWritesFiles, withNetwork("none"), withFileWrites("default prompt generation writes no project files and uses clipboard/output behavior", "--now writes project_refresh.constitution cadence state to .kit.yaml; docs/CONSTITUTION.md is never rewritten automatically"), withGitMutation("none"), withFlags(flag("--now", "mark the reviewed Constitution refresh complete in .kit.yaml"), flag("--constitution-only", "scope the generated prompt to docs/CONSTITUTION.md only"), flag("--output-only", "print the prompt instead of copying it", "read-only"), flag("--copy", "copy prompt even with --output-only")), withRelated(related("prompt project refresh", "prompt-library rendering path for the same default prompt"), related("check --project", "warns when the Constitution refresh cadence is overdue"), related("reconcile", "structural scaffold and registry refresh, not semantic Constitution learning")), withWhenToUse("Use after several completed features or whenever durable project rules, vocabulary, constraints, conventions, or workflow changes should be considered for docs/CONSTITUTION.md.", "Use `--now` only after a reviewed semantic refresh is complete."), withWhenNotToUse("Do not use as an automatic changelog or blind Constitution rewrite.", "Do not use instead of `kit reconcile --all --include-files` for structural scaffold, registry, or generated instruction-file refresh."), withExamples("kit project refresh", "kit project refresh --output-only", "kit project refresh --constitution-only --output-only", "kit project refresh --now"), withCaveats("Semantic documentation edits remain prompt-driven and reviewed; the command only generates guidance unless --now records cadence state.")),
		capability("rm", "Workflow", "Remove Kit-managed feature or state entries.", mutationDestructive, withFileWrites("removes or updates Kit-managed files depending on flags"), withAliases("remove"), withFlags(flag("--dry-run", "preview removals before changing files", "use before destructive cleanup")), withRelated(related("status", "inspect state before removal"))),
	}
}
