package cli

import (
	"fmt"
	"strings"

	"github.com/jamesonstone/kit/v3/internal/legacy"
	"github.com/jamesonstone/kit/v3/internal/templates"
)

// entryMigration is the planned state of one agent entry file.
type entryMigration struct {
	content   string
	converged bool   // carries exactly one current managed block afterwards
	note      string // why the file was left unchanged, when it was
}

// migrateEntryFile converges an existing agent entry file on exactly one
// current managed contract block while preserving project guidance:
//   - a file with the block has only the block replaced, and extra copies of
//     the block are dropped;
//   - a file with incomplete markers is left unchanged;
//   - a pre-contract file generated by an earlier Kit loses its Kit sections
//     and keeps every section Kit never wrote, below the block;
//   - Kit sections that someone edited block migration unless forced, which
//     discards those edits and still keeps project sections;
//   - a file with no Kit content gains the block under its own title.
func migrateEntryFile(relativePath, existing string, force bool) entryMigration {
	block := templates.UniversalContractBlock()
	begins := strings.Count(existing, templates.UniversalContractBeginMarker)
	ends := strings.Count(existing, templates.UniversalContractEndMarker)
	if begins > 0 || ends > 0 {
		content, ok := replaceManagedBlocks(existing, block)
		if !ok {
			return entryMigration{content: existing, note: fmt.Sprintf(
				"%s has incomplete Kit-managed contract markers and was left unchanged; restore the matching %s/%s pair or remove both, then rerun `kit reconcile`",
				relativePath, templates.UniversalContractBeginMarker, templates.UniversalContractEndMarker)}
		}
		return entryMigration{content: content, converged: true}
	}

	doc := legacy.Classify(relativePath, existing)
	if len(doc.Modified) > 0 && !force {
		return entryMigration{content: existing, note: fmt.Sprintf(
			"%s predates the Kit-managed contract and has edited Kit sections (%s); it was left unchanged. Review them, then run `kit reconcile --force` to replace Kit's sections with the contract (sections Kit never wrote are kept)",
			relativePath, strings.Join(doc.ModifiedKeys(), ", "))}
	}

	title := "# " + templates.InstructionEntryTitle(relativePath)
	if !kitWroteAnySection(doc) {
		// Entirely project-authored: keep its own title and every line.
		ownTitle, rest := splitEntryTitle(existing)
		if ownTitle != "" {
			title = ownTitle
		}
		return entryMigration{content: joinEntryFile(title, block, rest), converged: true}
	}
	var project strings.Builder
	for _, section := range doc.Project {
		project.WriteString(section.Raw)
		if !strings.HasSuffix(section.Raw, "\n") {
			project.WriteString("\n")
		}
	}
	return entryMigration{content: joinEntryFile(title, block, project.String()), converged: true}
}

// kitWroteAnySection ignores the title line, which every Markdown file has.
func kitWroteAnySection(doc legacy.Document) bool {
	for _, section := range doc.Kit {
		if section.Key != "" || !strings.HasPrefix(section.Text, "# ") || strings.Contains(section.Text, "\n") {
			return true
		}
	}
	return len(doc.Modified) > 0
}

func splitEntryTitle(content string) (string, string) {
	trimmed := strings.TrimLeft(content, "\n")
	line, rest, _ := strings.Cut(trimmed, "\n")
	if strings.HasPrefix(line, "# ") {
		return line, rest
	}
	return "", content
}

func joinEntryFile(title, block, project string) string {
	content := title + "\n\n" + block
	if project = strings.TrimSpace(project); project != "" {
		content += "\n" + project + "\n"
	}
	return content
}

// replaceManagedBlocks replaces the first complete block and drops later
// complete copies. It fails when any marker is unpaired.
func replaceManagedBlocks(content, block string) (string, bool) {
	var out strings.Builder
	rest := content
	replaced := false
	for {
		start := strings.Index(rest, templates.UniversalContractBeginMarker)
		end := strings.Index(rest, templates.UniversalContractEndMarker)
		if start < 0 && end < 0 {
			out.WriteString(rest)
			return out.String(), replaced
		}
		if start < 0 || end < start {
			return content, false
		}
		stop := end + len(templates.UniversalContractEndMarker)
		if strings.Contains(rest[start+1:end], templates.UniversalContractBeginMarker) {
			return content, false
		}
		out.WriteString(rest[:start])
		rest = rest[stop:]
		if !replaced {
			out.WriteString(strings.TrimSuffix(block, "\n"))
			replaced = true
			continue
		}
		// Drop a duplicate block and collapse the blank lines around it.
		trimmed := strings.TrimRight(out.String(), "\n")
		rest = strings.TrimLeft(rest, "\n")
		out.Reset()
		out.WriteString(trimmed)
		if rest != "" {
			out.WriteString("\n\n")
		} else {
			out.WriteString("\n")
		}
	}
}
