package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jamesonstone/kit/internal/config"
	"github.com/jamesonstone/kit/internal/document"
)

func TestFeaturePromptCommandsExposePromptOnlyFlag(t *testing.T) {
	commandPaths := [][]string{
		{"legacy", "brainstorm"},
		{"spec"},
		{"legacy", "plan"},
		{"legacy", "tasks"},
		{"legacy", "implement"},
		{"legacy", "reflect"},
		{"reconcile"},
		{"handoff"},
	}

	for _, path := range commandPaths {
		cmd, _, err := rootCmd.Find(path)
		if err != nil {
			t.Fatalf("rootCmd.Find(%v) error = %v", path, err)
		}
		if cmd.Flags().Lookup("prompt-only") == nil {
			t.Fatalf("expected %q to expose --prompt-only", strings.Join(path, " "))
		}
	}

	skillMineCmd, _, err := rootCmd.Find([]string{"skill", "mine"})
	if err != nil {
		t.Fatalf("rootCmd.Find(skill mine) error = %v", err)
	}
	if skillMineCmd.Flags().Lookup("prompt-only") == nil {
		t.Fatalf("expected skill mine to expose --prompt-only")
	}
}

func TestRunSpecPromptOnly_RequiresExistingSpec(t *testing.T) {
	projectRoot := t.TempDir()
	writeFile(t, filepath.Join(projectRoot, ".kit.yaml"), defaultKitConfig())
	writeFile(t, filepath.Join(projectRoot, "docs", "specs", "0001-sample", "BRAINSTORM.md"), "# BRAINSTORM\n")

	err := runSpecPromptOnly([]string{"sample"}, projectRoot, config.Default(), true)
	if err == nil || !strings.Contains(err.Error(), "SPEC.md not found") {
		t.Fatalf("expected missing SPEC.md error, got %v", err)
	}
}

func TestRunSpecPromptOnlyDoesNotWriteV2Adoption(t *testing.T) {
	projectRoot := t.TempDir()
	writeFile(t, filepath.Join(projectRoot, ".kit.yaml"), defaultKitConfig())
	specPath := filepath.Join(projectRoot, "docs", "specs", "0001-sample", "SPEC.md")
	original := "# SPEC\n\n## SUMMARY\n\nlegacy summary\n"
	writeFile(t, specPath, original)

	output := captureStdout(t, func() {
		if err := runSpecPromptOnly([]string{"sample"}, projectRoot, config.Default(), true); err != nil {
			t.Fatalf("runSpecPromptOnly() error = %v", err)
		}
	})

	got, err := os.ReadFile(specPath)
	if err != nil {
		t.Fatalf("os.ReadFile(%q) error = %v", specPath, err)
	}
	if string(got) != original {
		t.Fatalf("expected --prompt-only to leave SPEC.md unchanged, got:\n%s", string(got))
	}
	if _, err := os.Stat(filepath.Join(projectRoot, "docs", "notes", "0001-sample")); !os.IsNotExist(err) {
		t.Fatalf("expected --prompt-only to avoid creating notes directory, got %v", err)
	}
	if !strings.Contains(output, "This prompt was generated by `kit spec --prompt-only`") {
		t.Fatalf("expected prompt-only mode warning, got:\n%s", output)
	}
	assertV2SpecPromptContract(t, output)
	assertV2SpecPromptExcludesV1StageAssumptions(t, output)
}

func TestEnsureSpecV2AdoptionAddsMetadataAndMissingSections(t *testing.T) {
	projectRoot := t.TempDir()
	specPath := filepath.Join(projectRoot, "docs", "specs", "0001-sample", "SPEC.md")
	writeFile(t, specPath, "# SPEC\n\n## SUMMARY\n\nlegacy summary\n\n## PROBLEM\n\nlegacy problem\n")

	changed, err := ensureSpecV2Adoption(specPath, projectRoot, "0001-sample", 95)
	if err != nil {
		t.Fatalf("ensureSpecV2Adoption() error = %v", err)
	}
	if !changed {
		t.Fatal("expected v2 adoption to write metadata and missing sections")
	}

	content, err := os.ReadFile(specPath)
	if err != nil {
		t.Fatalf("os.ReadFile(%q) error = %v", specPath, err)
	}
	text := string(content)
	for _, check := range []string{
		"workflow_version: 2",
		"phase: clarify",
		"clarification:",
		"  status: open",
		"  confidence: 0",
		"  unresolved_questions: 1",
		"legacy summary",
		"legacy problem",
		"target: docs/notes/0001-sample",
	} {
		if !strings.Contains(text, check) {
			t.Fatalf("expected adopted SPEC.md to contain %q, got:\n%s", check, text)
		}
	}

	doc := document.Parse(text, specPath, document.TypeSpec)
	if doc.Metadata == nil || doc.Metadata.WorkflowVersion != 2 || doc.Metadata.Phase != "clarify" {
		t.Fatalf("expected v2 metadata, got %#v", doc.Metadata)
	}
	if clarification, ok := doc.ClarificationState(); !ok || clarification.Status != document.ClarificationStatusOpen {
		t.Fatalf("expected clarification metadata, got %#v ok=%v", clarification, ok)
	}
	for _, section := range doc.RequiredSections() {
		if !doc.HasSection(section) {
			t.Fatalf("expected adopted SPEC.md to contain v2 section %q, got:\n%s", section, text)
		}
	}
}

func TestRunPlanPromptOnly_RequiresExistingPlan(t *testing.T) {
	projectRoot := t.TempDir()
	writeFile(t, filepath.Join(projectRoot, ".kit.yaml"), defaultKitConfig())
	writeFile(t, filepath.Join(projectRoot, "docs", "specs", "0001-sample", "SPEC.md"), "# SPEC\n")

	err := runPlanPromptOnly([]string{"sample"}, projectRoot, config.Default(), false, true)
	if err == nil || !strings.Contains(err.Error(), "PLAN.md not found") {
		t.Fatalf("expected missing PLAN.md error, got %v", err)
	}
}

func TestRunTasksPromptOnly_RequiresExistingTasks(t *testing.T) {
	projectRoot := t.TempDir()
	writeFile(t, filepath.Join(projectRoot, ".kit.yaml"), defaultKitConfig())
	writeFile(t, filepath.Join(projectRoot, "docs", "specs", "0001-sample", "SPEC.md"), "# SPEC\n")
	writeFile(t, filepath.Join(projectRoot, "docs", "specs", "0001-sample", "PLAN.md"), "# PLAN\n")

	err := runTasksPromptOnly([]string{"sample"}, projectRoot, config.Default(), true)
	if err == nil || !strings.Contains(err.Error(), "TASKS.md not found") {
		t.Fatalf("expected missing TASKS.md error, got %v", err)
	}
}
