package cli

func v2GuidanceExpectations() map[string][]string {
	return map[string][]string{
		"docs/agents/README.md": {
			"## Runtime Routing",
			"load only the linked doc needed for the current decision",
			"Stop loading once the decision is supported",
		},
		"docs/agents/RLM.md": {
			"## Runtime Loop",
			"identify the immediate decision",
			"load the smallest relevant artifact",
			"stop loading once the decision is supported",
			"## Context Budget Rules",
			"specific section over full file",
			"repo-local docs before global model/vendor instructions",
			"Load `docs/references/rules/human-authorship.md` before any commit, pull request, issue, review comment, or other attribution text",
			"Load `docs/references/rules/testing-and-environment-validation.md` and `docs/references/testing.md` before implementation or validation, including browser automation and browser testing",
			"Load `docs/references/rules/deadline-mode.md` only when the user explicitly signals a real time constraint or deadline in-thread; never infer or proactively suggest deadline mode",
			"Load `docs/references/rules/deletion-safety.md` before designing deletion behavior or deleting persistent project, user, business, or external-system state",
			"Load `docs/references/rules/aws-agent-toolkit-guidance.md` before AWS-dependent work",
			"Load `docs/references/rules/infrastructure-change-approval.md` before planning or performing mutations to public-cloud resources, Kubernetes resources or cluster state, or infrastructure-as-code source, configuration, or state",
			"Load `docs/references/rules/cross-repository-program-coordination.md` before implementing or resuming an accepted plan that spans multiple repositories with dependent deliverables, staged deployment or activation, or expected agent or session handoff",
			"Load `docs/references/rules/agent-completion-output.md` before a substantial terminal completion or handoff response",
		},
		"docs/agents/TOOLING.md": {
			"When `cross-repository-program-coordination` applies, dispatch only the canonical program ledger's reconciled ready frontier and checkpoint program state after each material transition or handoff",
		},
		"docs/agents/WORKFLOWS.md": {
			"Authority order:",
			"Execution order for feature work:",
			"`SPEC.md` controls requirements, plan, tasks, validation, reflection, delivery, and evidence",
			"`BRAINSTORM.md`, `PLAN.md`, and `TASKS.md` are non-binding historical context in v2",
		},
		"docs/agents/GUARDRAILS.md": {
			"Never claim tests passed unless they ran",
			"Never claim files were inspected unless they were inspected",
			"If validation cannot run, state why",
			"docs/references/rules/source-file-size.md",
			"version-control-eligible handwritten implementation/source and test file at 300 physical lines or less",
		},
		"docs/references/README.md": {
			"`rules/agent-completion-output.md`",
			"`rules/human-authorship.md`",
			"`rules/deadline-mode.md`",
			"`rules/aws-agent-toolkit-guidance.md`",
			"`rules/deletion-safety.md`",
			"`rules/infrastructure-change-approval.md`",
			"`rules/cross-repository-program-coordination.md`",
			"`rules/testing-and-environment-validation.md`",
			"`rules/source-file-size.md`",
		},
		"docs/references/testing.md": {
			"`rules/testing-and-environment-validation.md`",
			"## Code-Level Validation",
			"## High-Level Suites",
			"## Environment Preflights",
			"## Evidence And Retention",
			"## Known Gaps",
		},
	}
}

func v3GuidanceExpectations() map[string][]string {
	return map[string][]string{
		"AGENTS.md": {
			"Default to a new worklane without asking",
			"Continue an existing lane only when the user explicitly directs",
			"Never offer or ask the user to choose between lanes",
			"Treat exact existing-PR lifecycle work as continuation",
			"Never create coordination or corrective pull requests for scope-preserving work",
			"## Agent Completion Output Contract",
			"Answer ordinary conversational requests naturally",
			"Use the structured contract when omitting it could hide a blocker",
			"must not receive status tokens, canonical section headings, synthetic None items, task profiles, or repository-memory reporting",
			"Do not classify by word count, token count, elapsed time, or tool-call count",
			"emit exactly `## What happened`, `## Deviations`, and `## Next steps` in that order",
			"**Status: PASS|PARTIAL|BLOCKED|FAIL — <one-sentence outcome>.**",
			"Use one `**None.**` bullet when there are no deviations",
			"Use one `**None.**` bullet when no action remains",
			"three canonical sections without duplication",
			"## Codex Thread Initialization Hard Gate",
			"before the first commentary message",
			"First, call the available thread-title operation (`set_thread_title` when available)",
			"Second, call the available thread-pin operation (`set_thread_pinned` when available)",
			"Thread initialization: rename <status>; pin <status>.",
			"## Browser policy",
			"For interactive browser work, use Codex's built-in browser through `@Browser`.",
			"Do not use `@Chrome`, control my active Chrome profile, or launch external",
			"unless I explicitly request it.",
			"If `@Browser` is unavailable, report the limitation instead of silently",
			"When I explicitly authorize an external browser, terminate and verify all",
			"task-owned browser and automation processes before finishing.",
			"`docs/references/rules/aws-agent-toolkit-guidance.md`",
			"Treat the verified account, ARN, and Region as authoritative",
			"Use the verified configured profile and Region explicitly",
			"never use default, another discovered profile, or ambient credentials",
			"## Deletion Safety Hard Gate",
			"An unqualified delete means soft delete",
			"bounded selector first resolved to the exact current target set",
			"materialized target IDs or an immutable snapshot/version token",
			"obtain a specific manual confirmation from the human for those exact current targets",
			"Before mutating public-cloud resources, Kubernetes resources or cluster state, or infrastructure-as-code source, configuration, or state, load `docs/references/rules/infrastructure-change-approval.md`.",
			"Routine application operations on already-provisioned workloads are not infrastructure-approval batches when they stay inside the recorded standard deployment boundary.",
			"Before implementing or resuming an accepted plan that spans multiple repositories and includes dependent deliverables, staged deployment or activation, or expected agent or session handoff, load `docs/references/rules/cross-repository-program-coordination.md`.",
			"Standing merge/deploy authority covers only a named existing standard deployment workflow",
			"IAM, network topology, KMS, secrets",
			"Deleting, destroying, or removing infrastructure always requires explicit confirmation after the consolidated outline, even when the initial request asked for it; one confirmation covers every deletion named in that batch.",
			"After infrastructure confirmation, execute the exact approved batch and continue in one pass without routine command-by-command approval.",
			"Pause, hold, or revocation stops affected actions and dependents until explicit human resume.",
			"Before implementation or validation, including browser automation and browser testing, load `docs/references/rules/testing-and-environment-validation.md` and the project's `docs/references/testing.md`",
		},
		".github/copilot-instructions.md": {
			"Default to a new worklane without asking",
			"Continue an existing lane only when the user explicitly directs",
			"Never offer or ask the user to choose between lanes",
			"Treat exact existing-PR lifecycle work as continuation",
			"Never create coordination or corrective pull requests for scope-preserving work",
			"## Agent Completion Output Contract",
			"Answer ordinary conversational requests naturally",
			"Use the structured contract when omitting it could hide a blocker",
			"must not receive status tokens, canonical section headings, synthetic None items, task profiles, or repository-memory reporting",
			"Do not classify by word count, token count, elapsed time, or tool-call count",
			"emit exactly `## What happened`, `## Deviations`, and `## Next steps` in that order",
			"**Status: PASS|PARTIAL|BLOCKED|FAIL — <one-sentence outcome>.**",
			"Use one `**None.**` bullet when there are no deviations",
			"Use one `**None.**` bullet when no action remains",
			"three canonical sections without duplication",
			"`docs/references/rules/aws-agent-toolkit-guidance.md`",
			"If `.kit.yaml` defines an enabled AWS context, run `kit aws verify` before the first AWS-dependent command and again immediately before AWS mutation",
			"Treat the verified account, ARN, and Region as authoritative",
			"Use the verified configured profile and Region explicitly",
			"never use default, another discovered profile, or ambient credentials",
			"## Deletion Safety Hard Gate",
			"An unqualified delete means soft delete",
			"bounded selector first resolved to the exact current target set",
			"materialized target IDs or an immutable snapshot/version token",
			"obtain a specific manual confirmation from the human for those exact current targets",
			"Before mutating public-cloud resources, Kubernetes resources or cluster state, or infrastructure-as-code source, configuration, or state, load `docs/references/rules/infrastructure-change-approval.md`.",
			"Routine application operations on already-provisioned workloads are not infrastructure-approval batches when they stay inside the recorded standard deployment boundary.",
			"Before implementing or resuming an accepted plan that spans multiple repositories and includes dependent deliverables, staged deployment or activation, or expected agent or session handoff, load `docs/references/rules/cross-repository-program-coordination.md`.",
			"Deleting, destroying, or removing infrastructure always requires explicit confirmation after the consolidated outline, even when the initial request asked for it; one confirmation covers every deletion named in that batch.",
			"Standing merge/deploy authority covers only a named existing standard deployment workflow",
			"Pause, hold, or revocation stops affected actions and dependents until explicit human resume.",
			"Before implementation or validation, including browser automation and browser testing, load `docs/references/rules/testing-and-environment-validation.md` and the project's `docs/references/testing.md`",
			"end-to-end and live-integration suites supplement rather than replace them",
			"Before editing implementation/source or test files, load `docs/references/rules/source-file-size.md`",
			"version-control-eligible handwritten implementation/source and test file at 300 physical lines or less",
		},
		"docs/agents/README.md": {
			"## Runtime Routing",
			"default to a new worklane without asking",
			"exact existing-PR review, CI, base-refresh, and ordered-merge work",
			"Native agent planning owns research, clarification, design, and plan formation",
			"V1 and V2 artifacts remain supported legacy inputs",
		},
		"docs/agents/WORKFLOWS.md": {
			"## Agent-First Contract",
			"default to a new worklane without asking",
			"Existing-PR review, CI, base-refresh, and ordered-merge work",
			"kit context resolve --workflow <slug> --json",
			"Before code, create or adopt `docs/specs/<feature>/SPEC.md` when material rationale must survive",
			"Never mechanically rewrite a V2 spec into V3",
			"`kit dispatch` supports post-plan execution topology",
		},
		"docs/agents/RLM.md": {
			"## Runtime Loop",
			"identify the immediate decision",
			"stop loading once the decision is supported",
			"## Context Budget Rules",
			"Load `docs/references/rules/human-authorship.md` before any commit, pull request, issue, review comment, or other attribution text",
			"Load `docs/references/rules/testing-and-environment-validation.md` and `docs/references/testing.md` before implementation or validation, including browser automation and browser testing",
			"Load `docs/references/rules/deadline-mode.md` only when the user explicitly signals a real time constraint or deadline in-thread; never infer or proactively suggest deadline mode",
			"Load `docs/references/rules/deletion-safety.md` before designing deletion behavior or deleting persistent project, user, business, or external-system state",
			"Load `docs/references/rules/aws-agent-toolkit-guidance.md` before AWS-dependent work",
			"Load `docs/references/rules/infrastructure-change-approval.md` before planning or performing mutations to public-cloud resources, Kubernetes resources or cluster state, or infrastructure-as-code source, configuration, or state",
			"Load `docs/references/rules/cross-repository-program-coordination.md` before implementing or resuming an accepted plan that spans multiple repositories with dependent deliverables, staged deployment or activation, or expected agent or session handoff",
			"Load `docs/references/rules/agent-completion-output.md` before a substantial terminal completion or handoff response",
		},
		"docs/agents/TOOLING.md": {
			"Default to a new worklane without asking",
			"continue an existing lane only when the user",
			"Treat exact existing-PR review repair, CI repair, base refresh, and ordered",
			"create a coordinator or corrective pull request for scope-preserving work",
			"Use `kit dispatch` after native planning",
			"accepted plan needs a safe multi-lane execution topology",
			"When `cross-repository-program-coordination` applies, dispatch only the canonical program ledger's reconciled ready frontier and checkpoint program state after each material transition or handoff",
			"Link the primary checkout's `.env` and `.envrc` into writable lanes by default",
			"preserve a repository- or user-supplied `.envrc`",
			"Standing merge authority exists only when a human explicitly authorizes a bounded task, goal, or program",
			"may bind later-created in-scope PRs and refreshed heads",
		},
		"docs/agents/GUARDRAILS.md": {
			"Default to a new worklane without asking",
			"Continue an existing lane only when the user explicitly directs",
			"Never offer or ask the user to choose between lanes",
			"Exact existing pull requests targeted for review repair, CI repair, base",
			"create a coordination or corrective pull request for scope-preserving work",
			"## Agent Completion Output Contract",
			"Answer ordinary conversational requests naturally",
			"Use the structured contract when omitting it could hide a blocker",
			"must not receive status tokens, canonical section headings, synthetic None items, task profiles, or repository-memory reporting",
			"Do not classify by word count, token count, elapsed time, or tool-call count",
			"emit exactly `## What happened`, `## Deviations`, and `## Next steps` in that order",
			"Use at most one nested evidence layer and state each fact once",
			"three canonical sections without duplication",
			"## Repository Memory Completion Gate",
			"Create or adopt a spec before code when material rationale exists",
			"repository-memory decision, rationale, and artifact paths or `none` in one concise What happened bullet",
			"do not add a separate Repository Memory section",
			"docs/references/rules/source-file-size.md",
			"version-control-eligible handwritten implementation/source and test file at 300 physical lines or less",
			"`docs/references/rules/aws-agent-toolkit-guidance.md`",
			"`docs/references/rules/deletion-safety.md`",
			"post-outline specific manual confirmation before every hard delete",
			"Treat the returned account ID, ARN, and Region as authoritative",
			"Before mutating public-cloud resources, Kubernetes resources or cluster state, or infrastructure-as-code source, configuration, or state, load `docs/references/rules/infrastructure-change-approval.md`.",
			"Routine application operations on already-provisioned workloads are not infrastructure-approval batches when they stay inside the recorded standard deployment boundary.",
			"Deleting, destroying, or removing infrastructure always requires explicit confirmation after the consolidated outline, even when the initial request asked for it; one confirmation covers every deletion named in that batch.",
			"Standing merge/deploy authority covers only a named existing standard deployment workflow",
			"Pause, hold, or revocation stops affected actions and dependents until explicit human resume.",
		},
		"docs/references/README.md": {
			"default to a new worklane without asking",
			"preserve exact existing-PR lifecycle",
			"`rules/agent-completion-output.md`",
			"`rules/human-authorship.md`",
			"`rules/deadline-mode.md`",
			"`rules/aws-agent-toolkit-guidance.md`",
			"`rules/deletion-safety.md`",
			"`rules/infrastructure-change-approval.md`",
			"`rules/cross-repository-program-coordination.md`",
			"`rules/testing-and-environment-validation.md`",
			"`rules/source-file-size.md`",
			"`rules/codex-thread-initialization.md`",
			"`worktrees.md` for the canonical native Git worktree hierarchy",
			"environment ownership",
			"browser lifecycle ownership",
		},
		"docs/references/testing.md": {
			"`rules/testing-and-environment-validation.md`",
			"## Code-Level Validation",
			"## High-Level Suites",
			"## Environment Preflights",
			"## Evidence And Retention",
			"## Known Gaps",
		},
		"docs/references/worktrees.md": {
			"Native `git worktree` commands and ordinary filesystem operations define this",
			"## Target-Aware Kit Repair Commands",
			"Resolution proves the current clone owns the requested repository",
			"## Writable-Lane Environment Links",
			"Link each stable source into writable lanes by default",
			"Preserve a regular destination",
			"Never use `--force`, reset, clean, stash, or branch deletion",
		},
	}
}

const (
	legacyOperatorActionTableHeader = "| Type | Action required | Why | Continue with |"
	legacyStatusHeading             = "# PASS|PARTIAL|BLOCKED|FAIL — <one-sentence outcome>"
	legacyPrioritizedActionList     = "prioritized action list ordered Blocker, Incomplete, Next, Optional, then None"
)

func v3ForbiddenGuidance() map[string][]string {
	completion := []string{
		legacyOperatorActionTableHeader,
		legacyStatusHeading,
		legacyPrioritizedActionList,
	}
	workLane := []string{
		"Before I make any repository changes, should I create a new GitHub issue",
		"`c` means continue existing",
		"Wait for the explicit choice",
	}
	consent := []string{
		"never imply merge consent",
		"Merge only after a direct user request or accepted bounded merge plan names the exact authorized PR set",
		"Obtain one explicit user confirmation for the complete bounded batch",
	}
	return map[string][]string{
		"AGENTS.md":                       append(append(completion, workLane...), consent...),
		".github/copilot-instructions.md": append(append(completion, workLane...), consent...),
		"docs/agents/GUARDRAILS.md":       append(append(completion, workLane...), consent...),
	}
}
