package cli

func v2GuidanceExpectations() map[string][]string {
	return map[string][]string{
		"docs/agents/README.md": {
			"## Runtime Routing",
			"load only the linked doc needed for the current decision",
			"Stop loading once the decision is supported",
		},
		"docs/agents/RLM.md": {
			"## Runtime Loop",
			"identify the immediate decision",
			"load the smallest relevant artifact",
			"stop loading once the decision is supported",
			"## Context Budget Rules",
			"specific section over full file",
			"repo-local docs before global model/vendor instructions",
			"Load `docs/references/rules/human-authorship.md` before any commit, pull request, issue, review comment, or other attribution text",
			"Load `docs/references/rules/testing-and-environment-validation.md` and `docs/references/testing.md` before implementation or validation, including browser automation and browser testing",
			"Load `docs/references/rules/deletion-safety.md` before designing deletion behavior or deleting persistent project, user, business, or external-system state",
			"Load `docs/references/rules/aws-agent-toolkit-guidance.md` before AWS-dependent work",
			"Load `docs/references/rules/infrastructure-change-approval.md` before planning or performing mutations to public-cloud resources, Kubernetes resources or cluster state, or infrastructure-as-code source, configuration, or state",
			"Load `docs/references/rules/cross-repository-program-coordination.md` before implementing or resuming an accepted plan that spans multiple repositories with dependent deliverables, staged deployment or activation, or expected agent or session handoff",
			"Load `docs/references/rules/agent-completion-output.md` before a terminal task completion or handoff response",
		},
		"docs/agents/TOOLING.md": {
			"When `cross-repository-program-coordination` applies, dispatch only the canonical program ledger's reconciled ready frontier and checkpoint program state after each material transition or handoff",
		},
		"docs/agents/WORKFLOWS.md": {
			"Authority order:",
			"Execution order for feature work:",
			"`SPEC.md` controls requirements, plan, tasks, validation, reflection, delivery, and evidence",
			"`BRAINSTORM.md`, `PLAN.md`, and `TASKS.md` are non-binding historical context in v2",
		},
		"docs/agents/GUARDRAILS.md": {
			"Never claim tests passed unless they ran",
			"Never claim files were inspected unless they were inspected",
			"If validation cannot run, state why",
			"docs/references/rules/source-file-size.md",
			"version-control-eligible handwritten implementation/source and test file at 300 physical lines or less",
		},
		"docs/references/README.md": {
			"`rules/agent-completion-output.md`",
			"`rules/human-authorship.md`",
			"`rules/aws-agent-toolkit-guidance.md`",
			"`rules/deletion-safety.md`",
			"`rules/infrastructure-change-approval.md`",
			"`rules/cross-repository-program-coordination.md`",
			"`rules/testing-and-environment-validation.md`",
			"`rules/source-file-size.md`",
		},
		"docs/references/testing.md": {
			"`rules/testing-and-environment-validation.md`",
			"## Code-Level Validation",
			"## High-Level Suites",
			"## Environment Preflights",
			"## Evidence And Retention",
			"## Known Gaps",
		},
	}
}

func v3GuidanceExpectations() map[string][]string {
	return map[string][]string{
		"AGENTS.md": {
			"## Agent Completion Output Contract",
			"# PASS|PARTIAL|BLOCKED|FAIL — <one-sentence outcome>",
			"Type | Action required | Why | Continue with",
			"After the action table, use left-aligned headings and CommonMark list or key/value blocks",
			"## Codex Thread Initialization Hard Gate",
			"before the first commentary message",
			"First, call the available thread-title operation (`set_thread_title` when available)",
			"Second, call the available thread-pin operation (`set_thread_pinned` when available)",
			"Thread initialization: rename <status>; pin <status>.",
			"## Browser policy",
			"For interactive browser work, use Codex's built-in browser through `@Browser`.",
			"Do not use `@Chrome`, control my active Chrome profile, or launch external",
			"unless I explicitly request it.",
			"If `@Browser` is unavailable, report the limitation instead of silently",
			"When I explicitly authorize an external browser, terminate and verify all",
			"task-owned browser and automation processes before finishing.",
			"`docs/references/rules/aws-agent-toolkit-guidance.md`",
			"Treat the verified account, ARN, and Region as authoritative",
			"Use the verified configured profile and Region explicitly",
			"never use default, another discovered profile, or ambient credentials",
			"## Deletion Safety Hard Gate",
			"An unqualified delete means soft delete",
			"bounded selector first resolved to the exact current target set",
			"materialized target IDs or an immutable snapshot/version token",
			"obtain a specific manual confirmation from the human for those exact current targets",
			"Before mutating public-cloud resources, Kubernetes resources or cluster state, or infrastructure-as-code source, configuration, or state, load `docs/references/rules/infrastructure-change-approval.md`.",
			"Before implementing or resuming an accepted plan that spans multiple repositories and includes dependent deliverables, staged deployment or activation, or expected agent or session handoff, load `docs/references/rules/cross-repository-program-coordination.md`.",
			"Put one consolidated outline of the target context, resource actions, execution boundary, material impact and risk, rollback or recovery, and validation evidence into the task plan when planning is used; otherwise present it once before the first covered mutation. Obtain one explicit user confirmation for the complete bounded batch.",
			"Deleting, destroying, or removing infrastructure always requires explicit confirmation after the consolidated outline, even when the initial request asked for it; one confirmation covers every deletion named in that batch.",
			"After confirmation, execute the exact approved batch and continue the rest of the task to completion in one pass without routine command-by-command approval.",
			"If additional covered infrastructure changes become necessary, collect all then-known changes into one follow-up outline, obtain one confirmation, and execute that follow-up batch in one pass. Do not re-confirm actions already included in an approved batch.",
			"Before implementation or validation, including browser automation and browser testing, load `docs/references/rules/testing-and-environment-validation.md` and the project's `docs/references/testing.md`",
		},
		".github/copilot-instructions.md": {
			"## Agent Completion Output Contract",
			"# PASS|PARTIAL|BLOCKED|FAIL — <one-sentence outcome>",
			"Type | Action required | Why | Continue with",
			"After the action table, use left-aligned headings and CommonMark list or key/value blocks",
			"`docs/references/rules/aws-agent-toolkit-guidance.md`",
			"If `.kit.yaml` defines an enabled AWS context, run `kit aws verify` before the first AWS-dependent command and again immediately before AWS mutation",
			"Treat the verified account, ARN, and Region as authoritative",
			"Use the verified configured profile and Region explicitly",
			"never use default, another discovered profile, or ambient credentials",
			"## Deletion Safety Hard Gate",
			"An unqualified delete means soft delete",
			"bounded selector first resolved to the exact current target set",
			"materialized target IDs or an immutable snapshot/version token",
			"obtain a specific manual confirmation from the human for those exact current targets",
			"Before mutating public-cloud resources, Kubernetes resources or cluster state, or infrastructure-as-code source, configuration, or state, load `docs/references/rules/infrastructure-change-approval.md`.",
			"Before implementing or resuming an accepted plan that spans multiple repositories and includes dependent deliverables, staged deployment or activation, or expected agent or session handoff, load `docs/references/rules/cross-repository-program-coordination.md`.",
			"Deleting, destroying, or removing infrastructure always requires explicit confirmation after the consolidated outline, even when the initial request asked for it; one confirmation covers every deletion named in that batch.",
			"If additional covered infrastructure changes become necessary, collect all then-known changes into one follow-up outline, obtain one confirmation, and execute that follow-up batch in one pass. Do not re-confirm actions already included in an approved batch.",
			"Before implementation or validation, including browser automation and browser testing, load `docs/references/rules/testing-and-environment-validation.md` and the project's `docs/references/testing.md`",
			"end-to-end and live-integration suites supplement rather than replace them",
			"Before editing implementation/source or test files, load `docs/references/rules/source-file-size.md`",
			"version-control-eligible handwritten implementation/source and test file at 300 physical lines or less",
		},
		"docs/agents/README.md": {
			"## Runtime Routing",
			"Native agent planning owns research, clarification, design, and plan formation",
			"V1 and V2 artifacts remain supported legacy inputs",
		},
		"docs/agents/WORKFLOWS.md": {
			"## Agent-First Contract",
			"kit context resolve --workflow <slug> --json",
			"Before code, create or adopt `docs/specs/<feature>/SPEC.md` when material rationale must survive",
			"Never mechanically rewrite a V2 spec into V3",
			"`kit dispatch` supports post-plan execution topology",
		},
		"docs/agents/RLM.md": {
			"## Runtime Loop",
			"identify the immediate decision",
			"stop loading once the decision is supported",
			"## Context Budget Rules",
			"Load `docs/references/rules/human-authorship.md` before any commit, pull request, issue, review comment, or other attribution text",
			"Load `docs/references/rules/testing-and-environment-validation.md` and `docs/references/testing.md` before implementation or validation, including browser automation and browser testing",
			"Load `docs/references/rules/deletion-safety.md` before designing deletion behavior or deleting persistent project, user, business, or external-system state",
			"Load `docs/references/rules/aws-agent-toolkit-guidance.md` before AWS-dependent work",
			"Load `docs/references/rules/infrastructure-change-approval.md` before planning or performing mutations to public-cloud resources, Kubernetes resources or cluster state, or infrastructure-as-code source, configuration, or state",
			"Load `docs/references/rules/cross-repository-program-coordination.md` before implementing or resuming an accepted plan that spans multiple repositories with dependent deliverables, staged deployment or activation, or expected agent or session handoff",
			"Load `docs/references/rules/agent-completion-output.md` before a terminal task completion or handoff response",
		},
		"docs/agents/TOOLING.md": {
			"Use `kit dispatch` after native planning",
			"accepted plan needs a safe multi-lane execution topology",
			"When `cross-repository-program-coordination` applies, dispatch only the canonical program ledger's reconciled ready frontier and checkpoint program state after each material transition or handoff",
			"Link the primary checkout's `.env` and `.envrc` into writable lanes by default",
			"preserve a repository- or user-supplied `.envrc`",
		},
		"docs/agents/GUARDRAILS.md": {
			"## Agent Completion Output Contract",
			"After the action table, use left-aligned headings and CommonMark list or key/value blocks",
			"implementation, research, diagnosis, planning, validation, review, operations, coordination, or fallback",
			"## Repository Memory Completion Gate",
			"Create or adopt a spec before code when material rationale exists",
			"Every implementation final response must include `Repository Memory`",
			"docs/references/rules/source-file-size.md",
			"version-control-eligible handwritten implementation/source and test file at 300 physical lines or less",
			"`docs/references/rules/aws-agent-toolkit-guidance.md`",
			"`docs/references/rules/deletion-safety.md`",
			"post-outline specific manual confirmation before every hard delete",
			"Treat the returned account ID, ARN, and Region as authoritative",
			"Before mutating public-cloud resources, Kubernetes resources or cluster state, or infrastructure-as-code source, configuration, or state, load `docs/references/rules/infrastructure-change-approval.md`.",
			"Deleting, destroying, or removing infrastructure always requires explicit confirmation after the consolidated outline, even when the initial request asked for it; one confirmation covers every deletion named in that batch.",
			"If additional covered infrastructure changes become necessary, collect all then-known changes into one follow-up outline, obtain one confirmation, and execute that follow-up batch in one pass. Do not re-confirm actions already included in an approved batch.",
		},
		"docs/references/README.md": {
			"`rules/agent-completion-output.md`",
			"`rules/human-authorship.md`",
			"`rules/aws-agent-toolkit-guidance.md`",
			"`rules/deletion-safety.md`",
			"`rules/infrastructure-change-approval.md`",
			"`rules/cross-repository-program-coordination.md`",
			"`rules/testing-and-environment-validation.md`",
			"`rules/source-file-size.md`",
			"`rules/codex-thread-initialization.md`",
			"`worktrees.md` for the canonical native Git worktree hierarchy",
			"environment ownership",
			"browser lifecycle ownership",
		},
		"docs/references/testing.md": {
			"`rules/testing-and-environment-validation.md`",
			"## Code-Level Validation",
			"## High-Level Suites",
			"## Environment Preflights",
			"## Evidence And Retention",
			"## Known Gaps",
		},
		"docs/references/worktrees.md": {
			"Native `git worktree` commands and ordinary filesystem operations define this",
			"## Target-Aware Kit Repair Commands",
			"Resolution proves the current clone owns the requested repository",
			"## Writable-Lane Environment Links",
			"Link each stable source into writable lanes by default",
			"Preserve a regular destination",
			"Never use `--force`, reset, clean, stash, or branch deletion",
		},
	}
}
