package cli

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jamesonstone/kit/internal/config"
)

func TestPhysicalLineCount(t *testing.T) {
	tests := []struct {
		name string
		data string
		want int
	}{
		{name: "empty", data: "", want: 0},
		{name: "terminated one line", data: "a\n", want: 1},
		{name: "unterminated one line", data: "a", want: 1},
		{name: "unterminated final line", data: "a\nb", want: 2},
		{name: "terminated two lines", data: "a\nb\n", want: 2},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := physicalLineCount([]byte(tt.data)); got != tt.want {
				t.Fatalf("physicalLineCount() = %d, want %d", got, tt.want)
			}
		})
	}
}

func TestGeneratedSourceContentRequiresHeaderComment(t *testing.T) {
	tests := []struct {
		name string
		data string
		want bool
	}{
		{name: "Go header", data: "// Code generated by fixture. DO NOT EDIT.\npackage sample\n", want: true},
		{name: "hash header", data: "# @generated\nvalue = 1\n", want: true},
		{name: "literal in handwritten test", data: "writeFixture(`// Code generated. DO NOT EDIT.`)\n", want: false},
		{name: "marker after header window", data: strings.Repeat("// license\n", 20) + "// @generated\n", want: false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := generatedSourceContent([]byte(tt.data)); got != tt.want {
				t.Fatalf("generatedSourceContent() = %t, want %t", got, tt.want)
			}
		})
	}
}

func TestAuditSourceFileSizesWithoutGitScopesFilesAndExclusions(t *testing.T) {
	projectRoot := t.TempDir()
	writeLines(t, filepath.Join(projectRoot, "main.go"), 301, "package main")
	writeLines(t, filepath.Join(projectRoot, "styles.scss"), 300, ".sample {}")
	writeLines(t, filepath.Join(projectRoot, "data.txt"), 301, "not source")
	writeLines(t, filepath.Join(projectRoot, "docs", "example.go"), 301, "package docs")
	writeLines(t, filepath.Join(projectRoot, ".kit", "state.go"), 301, "package kit")
	writeLines(t, filepath.Join(projectRoot, "vendor", "dep.go"), 301, "package dep")
	writeLines(t, filepath.Join(projectRoot, "generated.go"), 301, "// Code generated by fixture. DO NOT EDIT.")
	writeFile(t, filepath.Join(projectRoot, "binary.go"), "package main\x00"+strings.Repeat("\n", 301))
	outsidePath := filepath.Join(t.TempDir(), "outside.go")
	writeLines(t, outsidePath, 301, "package outside")
	if err := os.Symlink(outsidePath, filepath.Join(projectRoot, "linked.go")); err != nil {
		t.Fatalf("os.Symlink() error = %v", err)
	}
	scriptPath := filepath.Join(projectRoot, "tool")
	writeLines(t, scriptPath, 301, "#!/bin/sh")
	if err := os.Chmod(scriptPath, 0o755); err != nil {
		t.Fatalf("os.Chmod() error = %v", err)
	}

	findings := auditSourceFileSizes(projectRoot)
	if len(findings) != 2 {
		t.Fatalf("findings = %#v, want main.go and executable script", findings)
	}
	assertSourceFileFinding(t, findings, filepath.Join(projectRoot, "main.go"), 301)
	assertSourceFileFinding(t, findings, scriptPath, 301)
}

func TestAuditSourceFileSizesUsesGitVersionControlEligibleSet(t *testing.T) {
	projectRoot := t.TempDir()
	runGitForSourceAuditTest(t, projectRoot, "init", "-q")
	writeFile(t, filepath.Join(projectRoot, ".gitignore"), "ignored.py\n")
	writeLines(t, filepath.Join(projectRoot, "tracked.go"), 301, "package sample")
	writeLines(t, filepath.Join(projectRoot, "untracked.ts"), 302, "export const sample = true")
	writeLines(t, filepath.Join(projectRoot, "ignored.py"), 303, "value = True")
	runGitForSourceAuditTest(t, projectRoot, "add", ".gitignore", "tracked.go")

	findings := auditSourceFileSizes(projectRoot)
	if len(findings) != 2 {
		t.Fatalf("findings = %#v, want tracked and untracked non-ignored files", findings)
	}
	assertSourceFileFinding(t, findings, filepath.Join(projectRoot, "tracked.go"), 301)
	assertSourceFileFinding(t, findings, filepath.Join(projectRoot, "untracked.ts"), 302)
}

func TestAuditSourceFileSizesReportsGitEnumerationFailure(t *testing.T) {
	projectRoot := t.TempDir()
	writeFile(t, filepath.Join(projectRoot, ".git"), "not a worktree gitdir\n")
	writeLines(t, filepath.Join(projectRoot, "main.go"), 301, "package main")

	findings := auditSourceFileSizes(projectRoot)
	if len(findings) != 1 || !strings.Contains(findings[0].Issue, "source-file-size audit unavailable") {
		t.Fatalf("findings = %#v, want one unavailable-audit finding", findings)
	}
	if findings[0].AllowsCodeChanges {
		t.Fatalf("enumeration failure must not authorize source edits: %#v", findings[0])
	}
	result := inspectSourceFileSizes(projectRoot)
	if result.Summary.Complete || !strings.Contains(sourceFileAuditEvidence(&result.Summary), "clean result prohibited") {
		t.Fatalf("summary = %#v, want explicit incomplete evidence", result.Summary)
	}
}

func TestBuildReconcileReportIncludesWholeProjectSourceFileFindings(t *testing.T) {
	projectRoot := setupCoherentProjectForCheck(t)
	writeLines(t, filepath.Join(projectRoot, "main.go"), 301, "package main")
	cfg, err := config.Load(projectRoot)
	if err != nil {
		t.Fatalf("config.Load() error = %v", err)
	}

	report, err := buildReconcileReport(projectRoot, cfg, nil)
	if err != nil {
		t.Fatalf("buildReconcileReport() error = %v", err)
	}
	assertSourceFileFinding(t, report.Findings, filepath.Join(projectRoot, "main.go"), 301)
	if report.SourceFileAudit == nil || !report.SourceFileAudit.Complete || report.SourceFileAudit.ViolationCount != 1 {
		t.Fatalf("source audit = %#v, want complete audit with one violation", report.SourceFileAudit)
	}
}

func TestBuildReconcilePromptAuthorizesOnlyBoundedSourceSplits(t *testing.T) {
	projectRoot := t.TempDir()
	_, ok, _ := auditSourceFileSize(projectRoot, "main.go")
	if ok {
		t.Fatal("missing fixture must not produce source finding")
	}
	writeLines(t, filepath.Join(projectRoot, "main.go"), 301, "package main")
	finding, ok, _ := auditSourceFileSize(projectRoot, "main.go")
	if !ok {
		t.Fatal("oversized source fixture produced no finding")
	}

	prompt := buildReconcilePrompt(&reconcileReport{
		ProjectRoot: projectRoot,
		Findings:    []reconcileFinding{finding},
		SourceFileAudit: &sourceFileAuditSummary{
			CandidateCount: 1,
			EligibleCount:  1,
			ViolationCount: 1,
			Complete:       true,
		},
	})
	for _, want := range []string{
		"Reconcile Kit-managed project state for the whole project.",
		"source/test edits are authorized only for behavior-preserving semantic splits",
		"split by responsibility",
		"source file size",
		"source-file-size audit: complete",
		"No exact command-owned path snapshot is present",
	} {
		if !strings.Contains(prompt, want) {
			t.Fatalf("prompt missing %q:\n%s", want, prompt)
		}
	}
	if strings.Contains(prompt, "Only update Kit-managed docs and scaffold files") {
		t.Fatalf("source finding retained documentation-only rule:\n%s", prompt)
	}
}

func writeLines(t *testing.T, path string, count int, firstLine string) {
	t.Helper()
	content := firstLine + "\n"
	if count > 1 {
		content += strings.Repeat("line\n", count-1)
	}
	writeFile(t, path, content)
}

func runGitForSourceAuditTest(t *testing.T, projectRoot string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", append([]string{"-C", projectRoot}, args...)...)
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %v error = %v\n%s", args, err, output)
	}
}

func assertSourceFileFinding(t *testing.T, findings []reconcileFinding, path string, lines int) {
	t.Helper()
	for _, finding := range findings {
		if finding.FilePath != path {
			continue
		}
		if !finding.AllowsCodeChanges || !strings.Contains(finding.Issue, fmt.Sprintf("(%d)", lines)) {
			t.Fatalf("finding = %#v, want code-change finding with %d lines", finding, lines)
		}
		return
	}
	t.Fatalf("no source-file-size finding for %s: %#v", path, findings)
}
