package templates

import (
	_ "embed"
	"strings"
)

// Managed-block markers delimit the Kit-owned universal contract inside each
// agent entry file. Refresh replaces only the content between them.
const (
	UniversalContractBeginMarker = "<!-- BEGIN KIT-MANAGED CONTRACT -->"
	UniversalContractEndMarker   = "<!-- END KIT-MANAGED CONTRACT -->"
)

//go:embed universal_contract.md
var universalContractBody string

// UniversalContractBlock returns the single canonical Kit agent contract,
// wrapped in managed-block markers, shared by every agent entry file.
func UniversalContractBlock() string {
	return UniversalContractBeginMarker + "\n" +
		"<!-- Generated by Kit from its universal contract. Edit project guidance outside this block. -->\n\n" +
		strings.TrimSpace(universalContractBody) + "\n\n" +
		UniversalContractEndMarker + "\n"
}

// renderUniversalContract renders a vendor adapter: a title plus the shared block.
func renderUniversalContract(title string) string {
	return "# " + title + "\n\n" + UniversalContractBlock()
}
